//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
const COLUMNS: &[&str; 5usize] = &["uuid", "name", "cores", "ram", "disk"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("cores", crate::filter::FilterKind::I64),
    ("cores__gte", crate::filter::FilterKind::I64),
    ("cores__lte", crate::filter::FilterKind::I64),
    ("disk", crate::filter::FilterKind::I64),
    ("disk__gte", crate::filter::FilterKind::I64),
    ("disk__lte", crate::filter::FilterKind::I64),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("name_iregex", crate::filter::FilterKind::Str),
    ("offering_uuid", crate::filter::FilterKind::Str),
    ("ram", crate::filter::FilterKind::I64),
    ("ram__gte", crate::filter::FilterKind::I64),
    ("ram__lte", crate::filter::FilterKind::I64),
    ("settings", crate::filter::FilterKind::Str),
    ("settings_uuid", crate::filter::FilterKind::Str),
    ("tenant", crate::filter::FilterKind::Str),
    ("tenant_uuid", crate::filter::FilterKind::Str),
];
///OpenStack flavors (VM sizes)
#[derive(clap::Subcommand, Debug)]
pub enum FlavorCommand {
    ///List openstack flavors (vm sizes)
    List(FlavorListArgs),
    ///Get openstack flavors (vm sizes)
    Get(FlavorGetArgs),
    ///Wait for a --jmespath condition on openstack flavors (vm sizes)
    Wait(FlavorWaitArgs),
}
#[derive(clap::Args, Debug)]
pub struct FlavorListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["backend_id",
            "cores",
            "disk",
            "display_name",
            "name",
            "ram",
            "settings",
            "url",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
    ///Sort results server-side by these fields (comma-separated); prefix a field with - for descending, e.g. -created.
    #[arg(
        long = "order",
        value_delimiter = ',',
        allow_hyphen_values = true,
        value_parser = clap::builder::PossibleValuesParser::new(
            ["-cores",
            "-disk",
            "-ram",
            "cores",
            "disk",
            "ram"]
        ),
    )]
    pub order: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct FlavorGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct FlavorWaitArgs {
    pub uuid: String,
    /// JMESPath condition to poll for, evaluated against the
    /// fetched object on every poll (e.g. "state=='OK'").
    /// Waiting stops as soon as this evaluates to anything
    /// other than false or null.
    #[arg(long)]
    pub jmespath: String,
    /// Seconds to wait for the condition before giving up.
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
    /// Seconds between polls.
    #[arg(long, default_value_t = 3)]
    pub interval: u64,
}
pub async fn run(
    base_url: &str,
    token: Option<&str>,
    _project: Option<&str>,
    _dry_run: bool,
    command: FlavorCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        FlavorCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            if let Some(order) = &args.order {
                query_params.push(("o".to_string(), order.join(",")));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            if matches!(format, crate ::output::OutputFormat::Ndjson)
                && args.jmespath.is_none()
            {
                crate::pagination::fetch_all_streaming(
                        base_url,
                        token,
                        "/api/openstack-flavors/",
                        &query_params,
                        args.limit,
                        |item| crate::output::print_ndjson_line(&item),
                    )
                    .await?;
            } else {
                let result = crate::pagination::fetch_all(
                        base_url,
                        token,
                        "/api/openstack-flavors/",
                        &query_params,
                        args.limit,
                    )
                    .await?;
                let display_columns: Vec<&str> = match &args.fields {
                    Some(fields) => fields.iter().map(String::as_str).collect(),
                    None => COLUMNS.to_vec(),
                };
                let result: serde_json::Value = serde_json::Value::Array(result);
                let result = match &args.jmespath {
                    Some(expr) => crate::query::apply(result, expr)?,
                    None => result,
                };
                crate::output::print_result(&result, &display_columns, format)?;
            }
        }
        FlavorCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-flavors/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        FlavorCommand::Wait(args) => {
            let path = format!("{}{}{}", "/api/openstack-flavors/", args.uuid, "/");
            crate::wait::wait_for(
                    base_url,
                    token,
                    &path,
                    &args.jmespath,
                    args.timeout,
                    args.interval,
                    COLUMNS,
                    format,
                )
                .await?;
        }
    }
    Ok(())
}
