//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
const COLUMNS: &[&str; 4usize] = &["uuid", "address", "state", "project_name"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("address", crate::filter::FilterKind::Str),
    ("backend_id", crate::filter::FilterKind::Str),
    ("can_manage", crate::filter::FilterKind::Bool),
    ("customer", crate::filter::FilterKind::Str),
    ("customer_abbreviation", crate::filter::FilterKind::Str),
    ("customer_name", crate::filter::FilterKind::Str),
    ("customer_native_name", crate::filter::FilterKind::Str),
    ("customer_uuid", crate::filter::FilterKind::Str),
    ("description", crate::filter::FilterKind::Str),
    ("external_ip", crate::filter::FilterKind::Str),
    ("free", crate::filter::FilterKind::Bool),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("project", crate::filter::FilterKind::Str),
    ("project_name", crate::filter::FilterKind::Str),
    ("project_uuid", crate::filter::FilterKind::Str),
    ("runtime_state", crate::filter::FilterKind::Str),
    ("service_settings_name", crate::filter::FilterKind::Str),
    ("service_settings_uuid", crate::filter::FilterKind::Str),
    ("state", crate::filter::FilterKind::Str),
    ("tenant", crate::filter::FilterKind::Str),
    ("tenant_uuid", crate::filter::FilterKind::Str),
];
///OpenStack floating IPs
#[derive(clap::Subcommand, Debug)]
pub enum FloatingIpCommand {
    ///List openstack floating ips
    List(FloatingIpListArgs),
    ///Get openstack floating ips
    Get(FloatingIpGetArgs),
    ///Delete openstack floating ips
    Delete(FloatingIpDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["access_url",
            "address",
            "backend_id",
            "backend_network_id",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_name",
            "customer_native_name",
            "customer_uuid",
            "description",
            "error_message",
            "error_traceback",
            "external_address",
            "instance_name",
            "instance_url",
            "instance_uuid",
            "is_limit_based",
            "is_usage_based",
            "marketplace_category_name",
            "marketplace_category_uuid",
            "marketplace_offering_name",
            "marketplace_offering_plugin_options",
            "marketplace_offering_type",
            "marketplace_offering_uuid",
            "marketplace_plan_uuid",
            "marketplace_resource_state",
            "marketplace_resource_uuid",
            "modified",
            "name",
            "port",
            "port_fixed_ips",
            "project",
            "project_name",
            "project_uuid",
            "resource_type",
            "router",
            "runtime_state",
            "service_name",
            "service_settings",
            "service_settings_error_message",
            "service_settings_state",
            "service_settings_uuid",
            "state",
            "tenant",
            "tenant_name",
            "tenant_uuid",
            "url",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    project: Option<&str>,
    dry_run: bool,
    command: FloatingIpCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        FloatingIpCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            if let Some(project) = project {
                if !query_params.iter().any(|(k, _)| k == "project_uuid") {
                    query_params.push(("project_uuid".to_string(), project.to_string()));
                }
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/openstack-floating-ips/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            let result: serde_json::Value = serde_json::Value::Array(result);
            let result = match &args.jmespath {
                Some(expr) => crate::query::apply(result, expr)?,
                None => result,
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        FloatingIpCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-floating-ips/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        FloatingIpCommand::Delete(args) => {
            let path = format!("{}{}{}", "/api/openstack-floating-ips/", args.uuid, "/");
            if dry_run {
                return crate::output::print_dry_run("DELETE", &path, None, format);
            }
            let _ = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::DELETE,
                    &path,
                    None,
                )
                .await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
