//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "address", "state", "project_name"];
///OpenStack floating IPs
#[derive(clap::Subcommand, Debug)]
pub enum FloatingIpCommand {
    ///List openstack floating ips
    List(FloatingIpListArgs),
    ///Get openstack floating ips
    Get(FloatingIpGetArgs),
    ///Delete openstack floating ips
    Delete(FloatingIpDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpListArgs {
    #[arg(long)]
    pub address: Option<String>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub free: Option<bool>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub runtime_state: Option<String>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    #[arg(long)]
    pub tenant: Option<String>,
    #[arg(long)]
    pub tenant_uuid: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    /// Only fetch these fields from the server (comma-separated),
    /// instead of the complete object -- avoids over-fetching.
    /// Table output always does this already (using its own
    /// display columns); for json/toon/tsv, which fetch the
    /// complete object by default, this narrows what they get too.
    #[arg(long, value_delimiter = ',')]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: FloatingIpCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        FloatingIpCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.address {
                query_params.push(("address".to_string(), v.clone()));
            }
            if let Some(v) = &args.backend_id {
                query_params.push(("backend_id".to_string(), v.clone()));
            }
            if let Some(v) = args.can_manage {
                query_params.push(("can_manage".to_string(), v.to_string()));
            }
            if let Some(v) = &args.customer {
                query_params.push(("customer".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_abbreviation {
                query_params.push(("customer_abbreviation".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_name {
                query_params.push(("customer_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_native_name {
                query_params.push(("customer_native_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_uuid {
                query_params.push(("customer_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.description {
                query_params.push(("description".to_string(), v.clone()));
            }
            if let Some(v) = &args.external_ip {
                query_params.push(("external_ip".to_string(), v.clone()));
            }
            if let Some(v) = args.free {
                query_params.push(("free".to_string(), v.to_string()));
            }
            if let Some(v) = &args.name {
                query_params.push(("name".to_string(), v.clone()));
            }
            if let Some(v) = &args.name_exact {
                query_params.push(("name_exact".to_string(), v.clone()));
            }
            if let Some(v) = &args.project {
                query_params.push(("project".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_name {
                query_params.push(("project_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_uuid {
                query_params.push(("project_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.runtime_state {
                query_params.push(("runtime_state".to_string(), v.clone()));
            }
            if let Some(v) = &args.service_settings_name {
                query_params.push(("service_settings_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.service_settings_uuid {
                query_params.push(("service_settings_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.tenant {
                query_params.push(("tenant".to_string(), v.clone()));
            }
            if let Some(v) = &args.tenant_uuid {
                query_params.push(("tenant_uuid".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/openstack-floating-ips/",
                    &query_params,
                    args.limit,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        FloatingIpCommand::Get(args) => {
            let result = client
                .openstack_floating_ips_retrieve(args.uuid.as_str(), None)
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        FloatingIpCommand::Delete(args) => {
            let _ = client.openstack_floating_ips_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
