//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "address", "state", "project_name"];
///OpenStack floating IPs
#[derive(clap::Subcommand, Debug)]
pub enum FloatingIpCommand {
    ///List openstack floating ips
    List(FloatingIpListArgs),
    ///Get openstack floating ips
    Get(FloatingIpGetArgs),
    ///Delete openstack floating ips
    Delete(FloatingIpDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpListArgs {
    #[arg(long)]
    pub address: Option<String>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub free: Option<bool>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub runtime_state: Option<String>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    #[arg(long)]
    pub tenant: Option<String>,
    #[arg(long)]
    pub tenant_uuid: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct FloatingIpDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: FloatingIpCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        FloatingIpCommand::List(args) => {
            let result = client
                .openstack_floating_ips_list(
                    args.address.as_deref(),
                    args.backend_id.as_deref(),
                    args.can_manage,
                    args.customer.as_deref(),
                    args.customer_abbreviation.as_deref(),
                    args.customer_name.as_deref(),
                    args.customer_native_name.as_deref(),
                    args.customer_uuid.as_deref(),
                    args.description.as_deref(),
                    args.external_ip.as_deref(),
                    None,
                    args.free,
                    args.name.as_deref(),
                    args.name_exact.as_deref(),
                    args.page,
                    args.page_size,
                    args.project.as_deref(),
                    args.project_name.as_deref(),
                    args.project_uuid.as_deref(),
                    args.runtime_state.as_deref(),
                    args.service_settings_name.as_deref(),
                    args.service_settings_uuid.as_deref(),
                    None,
                    args.tenant.as_deref(),
                    args.tenant_uuid.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        FloatingIpCommand::Get(args) => {
            let result = client
                .openstack_floating_ips_retrieve(args.uuid.as_str(), None)
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        FloatingIpCommand::Delete(args) => {
            let _ = client.openstack_floating_ips_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
            }
        }
    }
    Ok(())
}
