//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "project_name"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("attach_volume_uuid", crate::filter::FilterKind::Str),
    ("availability_zone_name", crate::filter::FilterKind::Str),
    ("backend_id", crate::filter::FilterKind::Str),
    ("can_manage", crate::filter::FilterKind::Bool),
    ("customer", crate::filter::FilterKind::Str),
    ("customer_abbreviation", crate::filter::FilterKind::Str),
    ("customer_name", crate::filter::FilterKind::Str),
    ("customer_native_name", crate::filter::FilterKind::Str),
    ("customer_uuid", crate::filter::FilterKind::Str),
    ("description", crate::filter::FilterKind::Str),
    ("external_ip", crate::filter::FilterKind::Str),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("project", crate::filter::FilterKind::Str),
    ("project_name", crate::filter::FilterKind::Str),
    ("project_uuid", crate::filter::FilterKind::Str),
    ("query", crate::filter::FilterKind::Str),
    ("runtime_state", crate::filter::FilterKind::Str),
    ("service_settings_name", crate::filter::FilterKind::Str),
    ("service_settings_uuid", crate::filter::FilterKind::Str),
    ("state", crate::filter::FilterKind::Str),
    ("tenant", crate::filter::FilterKind::Str),
    ("tenant_uuid", crate::filter::FilterKind::Str),
];
const UPDATE_SKELETON: &str = "{\n  \"description\": null,\n  \"name\": \"\"\n}";
const PROVISION_SKELETON: &str = "{\n  \"accepting_terms_of_service\": true,\n  \"attributes\": {\n    \"availability_zone\": null,\n    \"config_drive\": null,\n    \"connect_directly_to_external_network\": null,\n    \"data_volume_size\": null,\n    \"data_volume_type\": null,\n    \"data_volumes\": null,\n    \"description\": null,\n    \"flavor\": \"\",\n    \"floating_ips\": null,\n    \"image\": \"\",\n    \"name\": \"\",\n    \"ports\": [\n      {\n        \"fixed_ips\": null,\n        \"port\": null,\n        \"port_security_enabled\": null,\n        \"subnet\": null\n      }\n    ],\n    \"security_groups\": null,\n    \"server_group\": null,\n    \"ssh_public_key\": null,\n    \"system_volume_size\": 0,\n    \"system_volume_type\": null,\n    \"user_data\": null\n  },\n  \"callback_url\": null,\n  \"limits\": null,\n  \"offering\": \"\",\n  \"plan\": null,\n  \"project\": \"\",\n  \"request_comment\": null,\n  \"slug\": null,\n  \"start_date\": null,\n  \"type\": null\n}";
///OpenStack instances (VMs)
#[derive(clap::Subcommand, Debug)]
pub enum InstanceCommand {
    ///List openstack instances (vms)
    List(InstanceListArgs),
    ///Get openstack instances (vms)
    Get(InstanceGetArgs),
    ///Update openstack instances (vms)
    Update(InstanceUpdateArgs),
    ///Provision openstack instances (vms) via a marketplace order
    Provision(InstanceProvisionArgs),
    ///Terminate openstack instances (vms) via a marketplace order
    Terminate(InstanceTerminateArgs),
}
#[derive(clap::Args, Debug)]
pub struct InstanceListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["access_url",
            "action",
            "action_details",
            "availability_zone",
            "availability_zone_name",
            "backend_id",
            "config_drive",
            "connect_directly_to_external_network",
            "cores",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_name",
            "customer_native_name",
            "customer_uuid",
            "description",
            "disk",
            "error_message",
            "error_traceback",
            "external_address",
            "external_ips",
            "flavor_disk",
            "flavor_name",
            "floating_ips",
            "hypervisor_hostname",
            "image_name",
            "internal_ips",
            "is_limit_based",
            "is_usage_based",
            "key_fingerprint",
            "key_name",
            "latitude",
            "longitude",
            "marketplace_category_name",
            "marketplace_category_uuid",
            "marketplace_offering_name",
            "marketplace_offering_plugin_options",
            "marketplace_offering_type",
            "marketplace_offering_uuid",
            "marketplace_plan_uuid",
            "marketplace_resource_state",
            "marketplace_resource_uuid",
            "min_disk",
            "min_ram",
            "modified",
            "name",
            "ports",
            "project",
            "project_name",
            "project_uuid",
            "ram",
            "rancher_cluster",
            "resource_type",
            "runtime_state",
            "security_groups",
            "server_group",
            "service_name",
            "service_settings",
            "service_settings_error_message",
            "service_settings_state",
            "service_settings_uuid",
            "ssh_public_key",
            "start_time",
            "state",
            "tenant",
            "tenant_uuid",
            "url",
            "user_data",
            "uuid",
            "volumes"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct InstanceGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "instance_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct InstanceUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "instance_provision_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct InstanceProvisionArgs {
    /// The marketplace order body as inline JSON. Use
    /// --generate-skeleton for a template (offering/project plus
    /// this resource's typed attributes), or --request-file to
    /// read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the order body from a JSON or YAML file.
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable order template and exit, instead of
    /// submitting (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
    /// Submit the order and return immediately, without polling
    /// it to completion.
    #[arg(long)]
    pub no_wait: bool,
    /// Seconds to wait for the order to reach a terminal state
    /// before giving up (ignored with --no-wait).
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
}
#[derive(clap::Args, Debug)]
pub struct InstanceTerminateArgs {
    /// The marketplace resource UUID (a resource's
    /// `marketplace_resource_uuid` field, from get/list) -- not
    /// the plugin resource's own UUID.
    pub uuid: String,
    /// Optional termination attributes as inline JSON, e.g.
    /// '{"delete_volumes": true}'.
    #[arg(long)]
    pub request: Option<String>,
    /// Submit the termination and return immediately, without
    /// polling the order to completion.
    #[arg(long)]
    pub no_wait: bool,
    /// Seconds to wait for the termination order before giving
    /// up (ignored with --no-wait).
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    project: Option<&str>,
    dry_run: bool,
    command: InstanceCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        InstanceCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            if let Some(project) = project {
                if !query_params.iter().any(|(k, _)| k == "project_uuid") {
                    query_params.push(("project_uuid".to_string(), project.to_string()));
                }
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/openstack-instances/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            let result: serde_json::Value = serde_json::Value::Array(result);
            let result = match &args.jmespath {
                Some(expr) => crate::query::apply(result, expr)?,
                None => result,
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        InstanceCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-instances/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        InstanceCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::OpenStackInstanceRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/openstack-instances/", uuid, "/");
            if dry_run {
                return crate::output::print_dry_run("PUT", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        InstanceCommand::Provision(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(PROVISION_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::order::provision(
                    base_url,
                    token,
                    &body,
                    project,
                    dry_run,
                    !args.no_wait,
                    args.timeout,
                    format,
                )
                .await?;
        }
        InstanceCommand::Terminate(args) => {
            crate::order::terminate(
                    base_url,
                    token,
                    &args.uuid,
                    args.request.as_deref(),
                    dry_run,
                    !args.no_wait,
                    args.timeout,
                    format,
                )
                .await?;
        }
    }
    Ok(())
}
