//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "project_name"];
///OpenStack instances (VMs)
#[derive(clap::Subcommand, Debug)]
pub enum InstanceCommand {
    ///List openstack instances (vms)
    List(InstanceListArgs),
    ///Get openstack instances (vms)
    Get(InstanceGetArgs),
    ///Update openstack instances (vms)
    Update(InstanceUpdateArgs),
}
#[derive(clap::Args, Debug)]
pub struct InstanceListArgs {
    #[arg(long)]
    pub attach_volume_uuid: Option<String>,
    #[arg(long)]
    pub availability_zone_name: Option<String>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub o: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub runtime_state: Option<String>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    #[arg(long)]
    pub tenant: Option<String>,
    #[arg(long)]
    pub tenant_uuid: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct InstanceGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct InstanceUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
pub async fn run(
    client: &HttpClient,
    command: InstanceCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        InstanceCommand::List(args) => {
            let result = client
                .openstack_instances_list(
                    args.attach_volume_uuid.as_deref(),
                    args.availability_zone_name.as_deref(),
                    args.backend_id.as_deref(),
                    args.can_manage,
                    args.customer.as_deref(),
                    args.customer_abbreviation.as_deref(),
                    args.customer_name.as_deref(),
                    args.customer_native_name.as_deref(),
                    args.customer_uuid.as_deref(),
                    args.description.as_deref(),
                    args.external_ip.as_deref(),
                    None,
                    args.name.as_deref(),
                    args.name_exact.as_deref(),
                    args
                        .o
                        .as_deref()
                        .map(|s| serde_json::from_str::<
                            waldur_client::OpenStackInstanceOEnum,
                        >(s))
                        .transpose()
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(o)
                            )
                        })?,
                    args.page,
                    args.page_size,
                    args.project.as_deref(),
                    args.project_name.as_deref(),
                    args.project_uuid.as_deref(),
                    args.query.as_deref(),
                    args.runtime_state.as_deref(),
                    args.service_settings_name.as_deref(),
                    args.service_settings_uuid.as_deref(),
                    None,
                    args.tenant.as_deref(),
                    args.tenant_uuid.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        InstanceCommand::Get(args) => {
            let result = client
                .openstack_instances_retrieve(args.uuid.as_str(), None)
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        InstanceCommand::Update(args) => {
            let result = client
                .openstack_instances_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<
                        waldur_client::OpenStackInstanceRequest,
                    >(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
