//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "project_name"];
///OpenStack networks
#[derive(clap::Subcommand, Debug)]
pub enum NetworkCommand {
    ///List openstack networks
    List(NetworkListArgs),
    ///Get openstack networks
    Get(NetworkGetArgs),
    ///Update openstack networks
    Update(NetworkUpdateArgs),
    ///Delete openstack networks
    Delete(NetworkDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct NetworkListArgs {
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub direct_only: Option<bool>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub is_external: Option<bool>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub rbac_only: Option<bool>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    #[arg(long)]
    pub tenant: Option<String>,
    #[arg(long)]
    pub tenant_uuid: Option<String>,
    #[arg(long)]
    pub r#type: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct NetworkGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct NetworkUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct NetworkDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: NetworkCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        NetworkCommand::List(args) => {
            let result = client
                .openstack_networks_list(
                    args.backend_id.as_deref(),
                    args.can_manage,
                    args.customer.as_deref(),
                    args.customer_abbreviation.as_deref(),
                    args.customer_name.as_deref(),
                    args.customer_native_name.as_deref(),
                    args.customer_uuid.as_deref(),
                    args.description.as_deref(),
                    args.direct_only,
                    args.external_ip.as_deref(),
                    None,
                    args.is_external,
                    args.name.as_deref(),
                    args.name_exact.as_deref(),
                    args.page,
                    args.page_size,
                    args.project.as_deref(),
                    args.project_name.as_deref(),
                    args.project_uuid.as_deref(),
                    args.rbac_only,
                    args.service_settings_name.as_deref(),
                    args.service_settings_uuid.as_deref(),
                    None,
                    args.tenant.as_deref(),
                    args.tenant_uuid.as_deref(),
                    args.r#type.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        NetworkCommand::Get(args) => {
            let result = client
                .openstack_networks_retrieve(args.uuid.as_str(), None)
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        NetworkCommand::Update(args) => {
            let result = client
                .openstack_networks_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<
                        waldur_client::OpenStackNetworkRequest,
                    >(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        NetworkCommand::Delete(args) => {
            let _ = client.openstack_networks_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
            }
        }
    }
    Ok(())
}
