//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "project_name"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("backend_id", crate::filter::FilterKind::Str),
    ("can_manage", crate::filter::FilterKind::Bool),
    ("customer", crate::filter::FilterKind::Str),
    ("customer_abbreviation", crate::filter::FilterKind::Str),
    ("customer_name", crate::filter::FilterKind::Str),
    ("customer_native_name", crate::filter::FilterKind::Str),
    ("customer_uuid", crate::filter::FilterKind::Str),
    ("description", crate::filter::FilterKind::Str),
    ("direct_only", crate::filter::FilterKind::Bool),
    ("external_ip", crate::filter::FilterKind::Str),
    ("is_external", crate::filter::FilterKind::Bool),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("project", crate::filter::FilterKind::Str),
    ("project_name", crate::filter::FilterKind::Str),
    ("project_uuid", crate::filter::FilterKind::Str),
    ("rbac_only", crate::filter::FilterKind::Bool),
    ("service_settings_name", crate::filter::FilterKind::Str),
    ("service_settings_uuid", crate::filter::FilterKind::Str),
    ("state", crate::filter::FilterKind::Str),
    ("tenant", crate::filter::FilterKind::Str),
    ("tenant_uuid", crate::filter::FilterKind::Str),
    ("type", crate::filter::FilterKind::Str),
];
const UPDATE_SKELETON: &str = "{\n  \"description\": null,\n  \"name\": \"\"\n}";
const UPDATE_REQUEST_SCHEMA: &str = "{\"properties\":{\"description\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"}";
const CREATE_SUBNET_SKELETON: &str = "{\n  \"allocation_pools\": null,\n  \"cidr\": null,\n  \"description\": null,\n  \"disable_gateway\": null,\n  \"dns_nameservers\": null,\n  \"gateway_ip\": null,\n  \"host_routes\": null,\n  \"ipv6_address_mode\": null,\n  \"ipv6_ra_mode\": null,\n  \"name\": \"\",\n  \"router\": null,\n  \"skip_router_connection\": null\n}";
const CREATE_SUBNET_REQUEST_SCHEMA: &str = "{\"properties\":{\"allocation_pools\":{\"items\":{\"properties\":{\"end\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]},\"start\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]}},\"required\":[\"end\",\"start\"],\"type\":\"object\"},\"type\":\"array\"},\"cidr\":{\"type\":\"string\"},\"description\":{\"type\":\"string\"},\"disable_gateway\":{\"type\":\"boolean\"},\"dns_nameservers\":{\"items\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]},\"type\":\"array\"},\"gateway_ip\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]},\"host_routes\":{\"items\":{\"properties\":{\"destination\":{\"type\":\"string\"},\"nexthop\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]}},\"required\":[\"destination\",\"nexthop\"],\"type\":\"object\"},\"type\":\"array\"},\"ipv6_address_mode\":{\"oneOf\":[{\"enum\":[\"slaac\",\"dhcpv6-stateful\",\"dhcpv6-stateless\"]},{\"enum\":[\"null\"]}]},\"ipv6_ra_mode\":{\"oneOf\":[{\"enum\":[\"slaac\",\"dhcpv6-stateful\",\"dhcpv6-stateless\"]},{\"enum\":[\"null\"]}]},\"name\":{\"type\":\"string\"},\"router\":{\"format\":\"uri\",\"type\":\"string\"},\"skip_router_connection\":{\"type\":\"boolean\"}},\"required\":[\"name\"],\"type\":\"object\"}";
const SET_MTU_SKELETON: &str = "{\n  \"mtu\": 0\n}";
const SET_MTU_REQUEST_SCHEMA: &str = "{\"properties\":{\"mtu\":{\"type\":\"integer\"}},\"required\":[\"mtu\"],\"type\":\"object\"}";
///OpenStack networks
#[derive(clap::Subcommand, Debug)]
pub enum NetworkCommand {
    ///List openstack networks
    List(NetworkListArgs),
    ///Get openstack networks
    Get(NetworkGetArgs),
    ///Update openstack networks
    Update(NetworkUpdateArgs),
    ///Delete openstack networks
    Delete(NetworkDeleteArgs),
    ///Wait for a --jmespath condition on openstack networks
    Wait(NetworkWaitArgs),
    ///Create subnet openstack networks
    CreateSubnet(NetworkCreateSubnetArgs),
    ///Set mtu openstack networks
    SetMtu(NetworkSetMtuArgs),
    ///Set ok openstack networks
    SetOk(NetworkSetOkArgs),
    ///Unlink openstack networks
    Unlink(NetworkUnlinkArgs),
}
#[derive(clap::Args, Debug)]
pub struct NetworkListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["access_url",
            "backend_id",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_name",
            "customer_native_name",
            "customer_uuid",
            "description",
            "error_message",
            "error_traceback",
            "is_external",
            "is_limit_based",
            "is_usage_based",
            "marketplace_category_name",
            "marketplace_category_uuid",
            "marketplace_offering_name",
            "marketplace_offering_plugin_options",
            "marketplace_offering_type",
            "marketplace_offering_uuid",
            "marketplace_plan_uuid",
            "marketplace_resource_state",
            "marketplace_resource_uuid",
            "modified",
            "mtu",
            "name",
            "port_security_enabled",
            "project",
            "project_name",
            "project_uuid",
            "rbac_policies",
            "resource_type",
            "segmentation_id",
            "service_name",
            "service_settings",
            "service_settings_error_message",
            "service_settings_state",
            "service_settings_uuid",
            "state",
            "subnets",
            "tenant",
            "tenant_name",
            "tenant_uuid",
            "type",
            "url",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct NetworkGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "network_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct NetworkUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct NetworkDeleteArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct NetworkWaitArgs {
    pub uuid: String,
    /// JMESPath condition to poll for, evaluated against the
    /// fetched object on every poll (e.g. "state=='OK'").
    /// Waiting stops as soon as this evaluates to anything
    /// other than false or null.
    #[arg(long)]
    pub jmespath: String,
    /// Seconds to wait for the condition before giving up.
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
    /// Seconds between polls.
    #[arg(long, default_value_t = 3)]
    pub interval: u64,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "network_create_subnet_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct NetworkCreateSubnetArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "network_set_mtu_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct NetworkSetMtuArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct NetworkSetOkArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct NetworkUnlinkArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
pub async fn run(
    base_url: &str,
    token: Option<&str>,
    project: Option<&str>,
    dry_run: bool,
    command: NetworkCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        NetworkCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            if let Some(project) = project {
                if !query_params.iter().any(|(k, _)| k == "project_uuid") {
                    query_params.push(("project_uuid".to_string(), project.to_string()));
                }
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            if matches!(format, crate ::output::OutputFormat::Ndjson)
                && args.jmespath.is_none()
            {
                crate::pagination::fetch_all_streaming(
                        base_url,
                        token,
                        "/api/openstack-networks/",
                        &query_params,
                        args.limit,
                        |item| crate::output::print_ndjson_line(&item),
                    )
                    .await?;
            } else {
                let result = crate::pagination::fetch_all(
                        base_url,
                        token,
                        "/api/openstack-networks/",
                        &query_params,
                        args.limit,
                    )
                    .await?;
                let display_columns: Vec<&str> = match &args.fields {
                    Some(fields) => fields.iter().map(String::as_str).collect(),
                    None => COLUMNS.to_vec(),
                };
                let result: serde_json::Value = serde_json::Value::Array(result);
                let result = match &args.jmespath {
                    Some(expr) => crate::query::apply(result, expr)?,
                    None => result,
                };
                crate::output::print_result(&result, &display_columns, format)?;
            }
        }
        NetworkCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-networks/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        NetworkCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(UPDATE_REQUEST_SCHEMA, &body)?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/openstack-networks/", uuid, "/");
            if dry_run {
                return crate::output::print_dry_run("PUT", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        NetworkCommand::Delete(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!("{}{}{}", "/api/openstack-networks/", uuid, "/");
                if dry_run {
                    crate::output::print_dry_run("DELETE", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::DELETE,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(_) => {
                        match format {
                            crate::output::OutputFormat::Json
                            | crate::output::OutputFormat::Ndjson => {
                                println!(
                                    "{}", serde_json::json!({ "deleted" : true, "uuid" : uuid })
                                );
                            }
                            crate::output::OutputFormat::Table => {
                                println!("Deleted {}", uuid);
                            }
                            crate::output::OutputFormat::Tsv => {
                                println!("true\t{}", uuid);
                            }
                            crate::output::OutputFormat::Toon => {
                                println!(
                                    "{}", serde_toon::to_string(& serde_json::json!({ "deleted"
                                    : true, "uuid" : uuid }),) ?
                                );
                            }
                        }
                    }
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        NetworkCommand::Wait(args) => {
            let path = format!("{}{}{}", "/api/openstack-networks/", args.uuid, "/");
            crate::wait::wait_for(
                    base_url,
                    token,
                    &path,
                    &args.jmespath,
                    args.timeout,
                    args.interval,
                    COLUMNS,
                    format,
                )
                .await?;
        }
        NetworkCommand::CreateSubnet(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SUBNET_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(CREATE_SUBNET_REQUEST_SCHEMA, &body)?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-networks/", uuid, "/create_subnet/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        NetworkCommand::SetMtu(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(SET_MTU_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(SET_MTU_REQUEST_SCHEMA, &body)?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/openstack-networks/", uuid, "/set_mtu/");
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        NetworkCommand::SetOk(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-networks/", uuid, "/set_ok/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        NetworkCommand::Unlink(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-networks/", uuid, "/unlink/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
    }
    Ok(())
}
