//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "network_name"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("admin_state_up", crate::filter::FilterKind::Bool),
    ("backend_id", crate::filter::FilterKind::Str),
    ("device_id", crate::filter::FilterKind::Str),
    ("device_owner", crate::filter::FilterKind::Str),
    ("exclude_subnet_uuids", crate::filter::FilterKind::Str),
    ("fixed_ips", crate::filter::FilterKind::Str),
    ("has_device_owner", crate::filter::FilterKind::Bool),
    ("mac_address", crate::filter::FilterKind::Str),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("network_name", crate::filter::FilterKind::Str),
    ("network_uuid", crate::filter::FilterKind::Str),
    ("query", crate::filter::FilterKind::Str),
    ("status", crate::filter::FilterKind::Str),
    ("tenant", crate::filter::FilterKind::Str),
    ("tenant_uuid", crate::filter::FilterKind::Str),
];
const CREATE_SKELETON: &str = "{\n  \"allowed_address_pairs\": null,\n  \"description\": null,\n  \"fixed_ips\": null,\n  \"mac_address\": null,\n  \"name\": \"\",\n  \"network\": null,\n  \"port_security_enabled\": null,\n  \"security_groups\": null,\n  \"target_tenant\": null\n}";
const CREATE_REQUEST_SCHEMA: &str = "{\"properties\":{\"allowed_address_pairs\":{\"items\":{\"properties\":{\"ip_address\":{\"type\":\"string\"},\"mac_address\":{\"type\":\"string\"}},\"required\":[],\"type\":\"object\"},\"type\":\"array\"},\"description\":{\"type\":\"string\"},\"fixed_ips\":{\"items\":{\"properties\":{\"ip_address\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]},\"subnet_id\":{\"type\":\"string\"}},\"required\":[\"ip_address\",\"subnet_id\"],\"type\":\"object\"},\"type\":\"array\"},\"mac_address\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"network\":{\"format\":\"uri\",\"type\":\"string\"},\"port_security_enabled\":{\"type\":\"boolean\"},\"security_groups\":{\"items\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"},\"type\":\"array\"},\"target_tenant\":{\"format\":\"uri\",\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"}";
const UPDATE_SKELETON: &str = "{\n  \"allowed_address_pairs\": null,\n  \"description\": null,\n  \"fixed_ips\": null,\n  \"mac_address\": null,\n  \"name\": \"\",\n  \"network\": null,\n  \"port_security_enabled\": null,\n  \"security_groups\": null,\n  \"target_tenant\": null\n}";
const UPDATE_REQUEST_SCHEMA: &str = "{\"properties\":{\"allowed_address_pairs\":{\"items\":{\"properties\":{\"ip_address\":{\"type\":\"string\"},\"mac_address\":{\"type\":\"string\"}},\"required\":[],\"type\":\"object\"},\"type\":\"array\"},\"description\":{\"type\":\"string\"},\"fixed_ips\":{\"items\":{\"properties\":{\"ip_address\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]},\"subnet_id\":{\"type\":\"string\"}},\"required\":[\"ip_address\",\"subnet_id\"],\"type\":\"object\"},\"type\":\"array\"},\"mac_address\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"network\":{\"format\":\"uri\",\"type\":\"string\"},\"port_security_enabled\":{\"type\":\"boolean\"},\"security_groups\":{\"items\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"},\"type\":\"array\"},\"target_tenant\":{\"format\":\"uri\",\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"}";
const SET_ALLOWED_ADDRESS_PAIRS_SKELETON: &str = "{\n  \"allowed_address_pairs\": [\n    {\n      \"ip_address\": \"\",\n      \"mac_address\": null\n    }\n  ]\n}";
const SET_ALLOWED_ADDRESS_PAIRS_REQUEST_SCHEMA: &str = "{\"properties\":{\"allowed_address_pairs\":{\"items\":{\"properties\":{\"ip_address\":{\"type\":\"string\"},\"mac_address\":{\"type\":\"string\"}},\"required\":[\"ip_address\"],\"type\":\"object\"},\"type\":\"array\"}},\"required\":[\"allowed_address_pairs\"],\"type\":\"object\"}";
const UPDATE_PORT_IP_SKELETON: &str = "{\n  \"ip_address\": \"\",\n  \"subnet\": \"\"\n}";
const UPDATE_PORT_IP_REQUEST_SCHEMA: &str = "{\"properties\":{\"ip_address\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]},\"subnet\":{\"format\":\"uri\",\"type\":\"string\"}},\"required\":[\"ip_address\",\"subnet\"],\"type\":\"object\"}";
const UPDATE_SECURITY_GROUPS_SKELETON: &str = "{\n  \"security_groups\": [\n    \"\"\n  ]\n}";
const UPDATE_SECURITY_GROUPS_REQUEST_SCHEMA: &str = "{\"properties\":{\"security_groups\":{\"items\":{\"format\":\"uri\",\"type\":\"string\"},\"type\":\"array\"}},\"required\":[\"security_groups\"],\"type\":\"object\"}";
///OpenStack ports
#[derive(clap::Subcommand, Debug)]
pub enum PortCommand {
    ///List openstack ports
    List(PortListArgs),
    ///Get openstack ports
    Get(PortGetArgs),
    ///Create openstack ports
    Create(PortCreateArgs),
    ///Update openstack ports
    Update(PortUpdateArgs),
    ///Delete openstack ports
    Delete(PortDeleteArgs),
    ///Wait for a --jmespath condition on openstack ports
    Wait(PortWaitArgs),
    ///Disable port openstack ports
    DisablePort(PortDisablePortArgs),
    ///Disable port security openstack ports
    DisablePortSecurity(PortDisablePortSecurityArgs),
    ///Enable port openstack ports
    EnablePort(PortEnablePortArgs),
    ///Enable port security openstack ports
    EnablePortSecurity(PortEnablePortSecurityArgs),
    ///Set allowed address pairs openstack ports
    SetAllowedAddressPairs(PortSetAllowedAddressPairsArgs),
    ///Set ok openstack ports
    SetOk(PortSetOkArgs),
    ///Unlink openstack ports
    Unlink(PortUnlinkArgs),
    ///Update port ip openstack ports
    UpdatePortIp(PortUpdatePortIpArgs),
    ///Update security groups openstack ports
    UpdateSecurityGroups(PortUpdateSecurityGroupsArgs),
}
#[derive(clap::Args, Debug)]
pub struct PortListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["access_url",
            "admin_state_up",
            "allowed_address_pairs",
            "backend_id",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_name",
            "customer_native_name",
            "customer_uuid",
            "description",
            "device_id",
            "device_owner",
            "error_message",
            "error_traceback",
            "fixed_ips",
            "floating_ips",
            "is_limit_based",
            "is_usage_based",
            "mac_address",
            "marketplace_category_name",
            "marketplace_category_uuid",
            "marketplace_offering_name",
            "marketplace_offering_plugin_options",
            "marketplace_offering_type",
            "marketplace_offering_uuid",
            "marketplace_plan_uuid",
            "marketplace_resource_state",
            "marketplace_resource_uuid",
            "modified",
            "name",
            "network",
            "network_name",
            "network_uuid",
            "port_security_enabled",
            "project",
            "project_name",
            "project_uuid",
            "resource_type",
            "security_groups",
            "service_name",
            "service_settings",
            "service_settings_error_message",
            "service_settings_state",
            "service_settings_uuid",
            "state",
            "status",
            "target_tenant",
            "tenant",
            "tenant_name",
            "tenant_uuid",
            "url",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
    ///Sort results server-side by these fields (comma-separated); prefix a field with - for descending, e.g. -created.
    #[arg(
        long = "order",
        value_delimiter = ',',
        allow_hyphen_values = true,
        value_parser = clap::builder::PossibleValuesParser::new(
            ["-admin_state_up",
            "-created",
            "-device_owner",
            "-instance_name",
            "-mac_address",
            "-name",
            "-network_name",
            "-status",
            "-subnet_name",
            "admin_state_up",
            "created",
            "device_owner",
            "instance_name",
            "mac_address",
            "name",
            "network_name",
            "status",
            "subnet_name"]
        ),
    )]
    pub order: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct PortGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "port_create_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct PortCreateArgs {
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "port_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct PortUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct PortDeleteArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct PortWaitArgs {
    pub uuid: String,
    /// JMESPath condition to poll for, evaluated against the
    /// fetched object on every poll (e.g. "state=='OK'").
    /// Waiting stops as soon as this evaluates to anything
    /// other than false or null.
    #[arg(long)]
    pub jmespath: String,
    /// Seconds to wait for the condition before giving up.
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
    /// Seconds between polls.
    #[arg(long, default_value_t = 3)]
    pub interval: u64,
}
#[derive(clap::Args, Debug)]
pub struct PortDisablePortArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct PortDisablePortSecurityArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct PortEnablePortArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct PortEnablePortSecurityArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "port_set_allowed_address_pairs_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct PortSetAllowedAddressPairsArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct PortSetOkArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct PortUnlinkArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "port_update_port_ip_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct PortUpdatePortIpArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "port_update_security_groups_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct PortUpdateSecurityGroupsArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
pub async fn run(
    base_url: &str,
    token: Option<&str>,
    _project: Option<&str>,
    dry_run: bool,
    command: PortCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        PortCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            if let Some(order) = &args.order {
                query_params.push(("o".to_string(), order.join(",")));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            if matches!(format, crate ::output::OutputFormat::Ndjson)
                && args.jmespath.is_none()
            {
                crate::pagination::fetch_all_streaming(
                        base_url,
                        token,
                        "/api/openstack-ports/",
                        &query_params,
                        args.limit,
                        |item| crate::output::print_ndjson_line(&item),
                    )
                    .await?;
            } else {
                let result = crate::pagination::fetch_all(
                        base_url,
                        token,
                        "/api/openstack-ports/",
                        &query_params,
                        args.limit,
                    )
                    .await?;
                let display_columns: Vec<&str> = match &args.fields {
                    Some(fields) => fields.iter().map(String::as_str).collect(),
                    None => COLUMNS.to_vec(),
                };
                let result: serde_json::Value = serde_json::Value::Array(result);
                let result = match &args.jmespath {
                    Some(expr) => crate::query::apply(result, expr)?,
                    None => result,
                };
                crate::output::print_result(&result, &display_columns, format)?;
            }
        }
        PortCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-ports/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        PortCommand::Create(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(CREATE_REQUEST_SCHEMA, &body)?;
            let path = "/api/openstack-ports/".to_string();
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        PortCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(UPDATE_REQUEST_SCHEMA, &body)?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/openstack-ports/", uuid, "/");
            if dry_run {
                return crate::output::print_dry_run("PUT", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        PortCommand::Delete(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!("{}{}{}", "/api/openstack-ports/", uuid, "/");
                if dry_run {
                    crate::output::print_dry_run("DELETE", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::DELETE,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(_) => {
                        match format {
                            crate::output::OutputFormat::Json
                            | crate::output::OutputFormat::Ndjson => {
                                println!(
                                    "{}", serde_json::json!({ "deleted" : true, "uuid" : uuid })
                                );
                            }
                            crate::output::OutputFormat::Table => {
                                println!("Deleted {}", uuid);
                            }
                            crate::output::OutputFormat::Tsv => {
                                println!("true\t{}", uuid);
                            }
                            crate::output::OutputFormat::Toon => {
                                println!(
                                    "{}", serde_toon::to_string(& serde_json::json!({ "deleted"
                                    : true, "uuid" : uuid }),) ?
                                );
                            }
                        }
                    }
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        PortCommand::Wait(args) => {
            let path = format!("{}{}{}", "/api/openstack-ports/", args.uuid, "/");
            crate::wait::wait_for(
                    base_url,
                    token,
                    &path,
                    &args.jmespath,
                    args.timeout,
                    args.interval,
                    COLUMNS,
                    format,
                )
                .await?;
        }
        PortCommand::DisablePort(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-ports/", uuid, "/disable_port/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        PortCommand::DisablePortSecurity(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-ports/", uuid, "/disable_port_security/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        PortCommand::EnablePort(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-ports/", uuid, "/enable_port/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        PortCommand::EnablePortSecurity(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-ports/", uuid, "/enable_port_security/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        PortCommand::SetAllowedAddressPairs(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(SET_ALLOWED_ADDRESS_PAIRS_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(
                SET_ALLOWED_ADDRESS_PAIRS_REQUEST_SCHEMA,
                &body,
            )?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-ports/", uuid, "/set_allowed_address_pairs/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        PortCommand::SetOk(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!("{}{}{}", "/api/openstack-ports/", uuid, "/set_ok/");
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        PortCommand::Unlink(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!("{}{}{}", "/api/openstack-ports/", uuid, "/unlink/");
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        PortCommand::UpdatePortIp(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_PORT_IP_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(UPDATE_PORT_IP_REQUEST_SCHEMA, &body)?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-ports/", uuid, "/update_port_ip/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        PortCommand::UpdateSecurityGroups(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SECURITY_GROUPS_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(
                UPDATE_SECURITY_GROUPS_REQUEST_SCHEMA,
                &body,
            )?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-ports/", uuid, "/update_security_groups/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
