//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "tenant_name"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("state", crate::filter::FilterKind::Str),
    ("tenant", crate::filter::FilterKind::Str),
    ("tenant_uuid", crate::filter::FilterKind::Str),
];
const CREATE_SKELETON: &str = "{\n  \"name\": \"\",\n  \"tenant\": \"\"\n}";
const CREATE_REQUEST_SCHEMA: &str = "{\"properties\":{\"name\":{\"type\":\"string\"},\"tenant\":{\"format\":\"uri\",\"type\":\"string\"}},\"required\":[\"name\",\"tenant\"],\"type\":\"object\"}";
const ADD_ROUTER_INTERFACE_SKELETON: &str = "{\n  \"port\": null,\n  \"subnet\": null\n}";
const ADD_ROUTER_INTERFACE_REQUEST_SCHEMA: &str = "{\"properties\":{\"port\":{\"format\":\"uri\",\"type\":\"string\"},\"subnet\":{\"format\":\"uri\",\"type\":\"string\"}},\"required\":[],\"type\":\"object\"}";
const REMOVE_ROUTER_INTERFACE_SKELETON: &str = "{\n  \"port\": null,\n  \"subnet\": null\n}";
const REMOVE_ROUTER_INTERFACE_REQUEST_SCHEMA: &str = "{\"properties\":{\"port\":{\"format\":\"uri\",\"type\":\"string\"},\"subnet\":{\"format\":\"uri\",\"type\":\"string\"}},\"required\":[],\"type\":\"object\"}";
const SET_EXTERNAL_GATEWAY_SKELETON: &str = "{\n  \"enable_snat\": null,\n  \"external_fixed_ips\": null,\n  \"external_network_id\": \"\"\n}";
const SET_EXTERNAL_GATEWAY_REQUEST_SCHEMA: &str = "{\"properties\":{\"enable_snat\":{\"type\":\"boolean\"},\"external_fixed_ips\":{\"items\":{\"properties\":{\"ip_address\":{\"type\":\"string\"},\"subnet_id\":{\"type\":\"string\"}},\"required\":[\"ip_address\"],\"type\":\"object\"},\"type\":\"array\"},\"external_network_id\":{\"type\":\"string\"}},\"required\":[\"external_network_id\"],\"type\":\"object\"}";
const SET_ROUTES_SKELETON: &str = "{\n  \"routes\": [\n    {\n      \"destination\": \"\",\n      \"nexthop\": \"\"\n    }\n  ]\n}";
const SET_ROUTES_REQUEST_SCHEMA: &str = "{\"properties\":{\"routes\":{\"items\":{\"properties\":{\"destination\":{\"type\":\"string\"},\"nexthop\":{\"oneOf\":[{\"format\":\"ipv4\",\"type\":\"string\"},{\"format\":\"ipv6\",\"type\":\"string\"}]}},\"required\":[\"destination\",\"nexthop\"],\"type\":\"object\"},\"type\":\"array\"}},\"required\":[\"routes\"],\"type\":\"object\"}";
///OpenStack routers
#[derive(clap::Subcommand, Debug)]
pub enum RouterCommand {
    ///List openstack routers
    List(RouterListArgs),
    ///Get openstack routers
    Get(RouterGetArgs),
    ///Create openstack routers
    Create(RouterCreateArgs),
    ///Delete openstack routers
    Delete(RouterDeleteArgs),
    ///Wait for a --jmespath condition on openstack routers
    Wait(RouterWaitArgs),
    ///Add router interface openstack routers
    AddRouterInterface(RouterAddRouterInterfaceArgs),
    ///Remove external gateway openstack routers
    RemoveExternalGateway(RouterRemoveExternalGatewayArgs),
    ///Remove router interface openstack routers
    RemoveRouterInterface(RouterRemoveRouterInterfaceArgs),
    ///Set external gateway openstack routers
    SetExternalGateway(RouterSetExternalGatewayArgs),
    ///Set ok openstack routers
    SetOk(RouterSetOkArgs),
    ///Set routes openstack routers
    SetRoutes(RouterSetRoutesArgs),
}
#[derive(clap::Args, Debug)]
pub struct RouterListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["access_url",
            "backend_id",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_name",
            "customer_native_name",
            "customer_uuid",
            "description",
            "enable_snat",
            "error_message",
            "error_traceback",
            "external_fixed_ips",
            "external_network_id",
            "external_network_name",
            "external_network_uuid",
            "fixed_ips",
            "has_external_gateway",
            "is_limit_based",
            "is_usage_based",
            "marketplace_category_name",
            "marketplace_category_uuid",
            "marketplace_offering_name",
            "marketplace_offering_plugin_options",
            "marketplace_offering_type",
            "marketplace_offering_uuid",
            "marketplace_plan_uuid",
            "marketplace_resource_state",
            "marketplace_resource_uuid",
            "modified",
            "name",
            "offering_external_ips",
            "ports",
            "project",
            "project_name",
            "project_uuid",
            "resource_type",
            "routes",
            "service_name",
            "service_settings",
            "service_settings_error_message",
            "service_settings_state",
            "service_settings_uuid",
            "state",
            "tenant",
            "tenant_name",
            "tenant_uuid",
            "url",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct RouterGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "router_create_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct RouterCreateArgs {
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct RouterDeleteArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
pub struct RouterWaitArgs {
    pub uuid: String,
    /// JMESPath condition to poll for, evaluated against the
    /// fetched object on every poll (e.g. "state=='OK'").
    /// Waiting stops as soon as this evaluates to anything
    /// other than false or null.
    #[arg(long)]
    pub jmespath: String,
    /// Seconds to wait for the condition before giving up.
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
    /// Seconds between polls.
    #[arg(long, default_value_t = 3)]
    pub interval: u64,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "router_add_router_interface_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct RouterAddRouterInterfaceArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct RouterRemoveExternalGatewayArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "router_remove_router_interface_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct RouterRemoveRouterInterfaceArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "router_set_external_gateway_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct RouterSetExternalGatewayArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct RouterSetOkArgs {
    /// UUID(s) to operate on. Omit to read them from stdin instead,
    /// one per line -- either a bare UUID or a JSON object with a
    /// `uuid` field, so piping `list --format ndjson` straight in
    /// works without an intermediate `jq -r .uuid`.
    pub uuid: Vec<String>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "router_set_routes_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct RouterSetRoutesArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for
    /// a template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead
    /// of sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
pub async fn run(
    base_url: &str,
    token: Option<&str>,
    _project: Option<&str>,
    dry_run: bool,
    command: RouterCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        RouterCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            if matches!(format, crate ::output::OutputFormat::Ndjson)
                && args.jmespath.is_none()
            {
                crate::pagination::fetch_all_streaming(
                        base_url,
                        token,
                        "/api/openstack-routers/",
                        &query_params,
                        args.limit,
                        |item| crate::output::print_ndjson_line(&item),
                    )
                    .await?;
            } else {
                let result = crate::pagination::fetch_all(
                        base_url,
                        token,
                        "/api/openstack-routers/",
                        &query_params,
                        args.limit,
                    )
                    .await?;
                let display_columns: Vec<&str> = match &args.fields {
                    Some(fields) => fields.iter().map(String::as_str).collect(),
                    None => COLUMNS.to_vec(),
                };
                let result: serde_json::Value = serde_json::Value::Array(result);
                let result = match &args.jmespath {
                    Some(expr) => crate::query::apply(result, expr)?,
                    None => result,
                };
                crate::output::print_result(&result, &display_columns, format)?;
            }
        }
        RouterCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-routers/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RouterCommand::Create(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(CREATE_REQUEST_SCHEMA, &body)?;
            let path = "/api/openstack-routers/".to_string();
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RouterCommand::Delete(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!("{}{}{}", "/api/openstack-routers/", uuid, "/");
                if dry_run {
                    crate::output::print_dry_run("DELETE", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::DELETE,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(_) => {
                        match format {
                            crate::output::OutputFormat::Json
                            | crate::output::OutputFormat::Ndjson => {
                                println!(
                                    "{}", serde_json::json!({ "deleted" : true, "uuid" : uuid })
                                );
                            }
                            crate::output::OutputFormat::Table => {
                                println!("Deleted {}", uuid);
                            }
                            crate::output::OutputFormat::Tsv => {
                                println!("true\t{}", uuid);
                            }
                            crate::output::OutputFormat::Toon => {
                                println!(
                                    "{}", serde_toon::to_string(& serde_json::json!({ "deleted"
                                    : true, "uuid" : uuid }),) ?
                                );
                            }
                        }
                    }
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        RouterCommand::Wait(args) => {
            let path = format!("{}{}{}", "/api/openstack-routers/", args.uuid, "/");
            crate::wait::wait_for(
                    base_url,
                    token,
                    &path,
                    &args.jmespath,
                    args.timeout,
                    args.interval,
                    COLUMNS,
                    format,
                )
                .await?;
        }
        RouterCommand::AddRouterInterface(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(ADD_ROUTER_INTERFACE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(
                ADD_ROUTER_INTERFACE_REQUEST_SCHEMA,
                &body,
            )?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-routers/", uuid, "/add_router_interface/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RouterCommand::RemoveExternalGateway(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-routers/", uuid,
                    "/remove_external_gateway/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        RouterCommand::RemoveRouterInterface(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(REMOVE_ROUTER_INTERFACE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(
                REMOVE_ROUTER_INTERFACE_REQUEST_SCHEMA,
                &body,
            )?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-routers/", uuid, "/remove_router_interface/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RouterCommand::SetExternalGateway(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(SET_EXTERNAL_GATEWAY_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(
                SET_EXTERNAL_GATEWAY_REQUEST_SCHEMA,
                &body,
            )?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-routers/", uuid, "/set_external_gateway/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RouterCommand::SetOk(args) => {
            let uuids = crate::batch::resolve_uuids(args.uuid)?;
            let mut failed = Vec::new();
            for uuid in uuids {
                let path = format!(
                    "{}{}{}", "/api/openstack-routers/", uuid, "/set_ok/"
                );
                if dry_run {
                    crate::output::print_dry_run("POST", &path, None, format)?;
                    continue;
                }
                match crate::http::call_one(
                        base_url,
                        token,
                        reqwest::Method::POST,
                        &path,
                        None,
                    )
                    .await
                {
                    Ok(result) => crate::output::print_result(&result, COLUMNS, format)?,
                    Err(err) => {
                        crate::batch::report_error(&uuid, &err);
                        failed.push(uuid);
                    }
                }
            }
            if !failed.is_empty() {
                anyhow::bail!(
                    "{} of the batch failed: {}", failed.len(), failed.join(", ")
                );
            }
        }
        RouterCommand::SetRoutes(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(SET_ROUTES_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(SET_ROUTES_REQUEST_SCHEMA, &body)?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!(
                "{}{}{}", "/api/openstack-routers/", uuid, "/set_routes/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
