//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "project_name"];
///OpenStack security groups
#[derive(clap::Subcommand, Debug)]
pub enum SecurityGroupCommand {
    ///List openstack security groups
    List(SecurityGroupListArgs),
    ///Get openstack security groups
    Get(SecurityGroupGetArgs),
    ///Update openstack security groups
    Update(SecurityGroupUpdateArgs),
    ///Delete openstack security groups
    Delete(SecurityGroupDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct SecurityGroupListArgs {
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    #[arg(long)]
    pub tenant: Option<String>,
    #[arg(long)]
    pub tenant_uuid: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct SecurityGroupGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct SecurityGroupUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct SecurityGroupDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: SecurityGroupCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        SecurityGroupCommand::List(args) => {
            let result = client
                .openstack_security_groups_list(
                    args.backend_id.as_deref(),
                    args.can_manage,
                    args.customer.as_deref(),
                    args.customer_abbreviation.as_deref(),
                    args.customer_name.as_deref(),
                    args.customer_native_name.as_deref(),
                    args.customer_uuid.as_deref(),
                    args.description.as_deref(),
                    args.external_ip.as_deref(),
                    None,
                    args.name.as_deref(),
                    args.name_exact.as_deref(),
                    args.page,
                    args.page_size,
                    args.project.as_deref(),
                    args.project_name.as_deref(),
                    args.project_uuid.as_deref(),
                    args.query.as_deref(),
                    args.service_settings_name.as_deref(),
                    args.service_settings_uuid.as_deref(),
                    None,
                    args.tenant.as_deref(),
                    args.tenant_uuid.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        SecurityGroupCommand::Get(args) => {
            let result = client
                .openstack_security_groups_retrieve(args.uuid.as_str(), None)
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        SecurityGroupCommand::Update(args) => {
            let result = client
                .openstack_security_groups_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<
                        waldur_client::OpenStackSecurityGroupUpdateRequest,
                    >(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        SecurityGroupCommand::Delete(args) => {
            let _ = client.openstack_security_groups_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
