//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "cidr"];
///OpenStack subnets
#[derive(clap::Subcommand, Debug)]
pub enum SubnetCommand {
    ///List openstack subnets
    List(SubnetListArgs),
    ///Get openstack subnets
    Get(SubnetGetArgs),
    ///Update openstack subnets
    Update(SubnetUpdateArgs),
    ///Delete openstack subnets
    Delete(SubnetDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct SubnetListArgs {
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub direct_only: Option<bool>,
    #[arg(long)]
    pub enable_dhcp: Option<bool>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub ip_version: Option<i64>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub network: Option<String>,
    #[arg(long)]
    pub network_uuid: Option<String>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub rbac_only: Option<bool>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    #[arg(long)]
    pub tenant: Option<String>,
    #[arg(long)]
    pub tenant_uuid: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
}
#[derive(clap::Args, Debug)]
pub struct SubnetGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct SubnetUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct SubnetDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: SubnetCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        SubnetCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.backend_id {
                query_params.push(("backend_id".to_string(), v.clone()));
            }
            if let Some(v) = args.can_manage {
                query_params.push(("can_manage".to_string(), v.to_string()));
            }
            if let Some(v) = &args.customer {
                query_params.push(("customer".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_abbreviation {
                query_params.push(("customer_abbreviation".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_name {
                query_params.push(("customer_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_native_name {
                query_params.push(("customer_native_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_uuid {
                query_params.push(("customer_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.description {
                query_params.push(("description".to_string(), v.clone()));
            }
            if let Some(v) = args.direct_only {
                query_params.push(("direct_only".to_string(), v.to_string()));
            }
            if let Some(v) = args.enable_dhcp {
                query_params.push(("enable_dhcp".to_string(), v.to_string()));
            }
            if let Some(v) = &args.external_ip {
                query_params.push(("external_ip".to_string(), v.clone()));
            }
            if let Some(v) = args.ip_version {
                query_params.push(("ip_version".to_string(), v.to_string()));
            }
            if let Some(v) = &args.name {
                query_params.push(("name".to_string(), v.clone()));
            }
            if let Some(v) = &args.name_exact {
                query_params.push(("name_exact".to_string(), v.clone()));
            }
            if let Some(v) = &args.network {
                query_params.push(("network".to_string(), v.clone()));
            }
            if let Some(v) = &args.network_uuid {
                query_params.push(("network_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.project {
                query_params.push(("project".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_name {
                query_params.push(("project_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_uuid {
                query_params.push(("project_uuid".to_string(), v.clone()));
            }
            if let Some(v) = args.rbac_only {
                query_params.push(("rbac_only".to_string(), v.to_string()));
            }
            if let Some(v) = &args.service_settings_name {
                query_params.push(("service_settings_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.service_settings_uuid {
                query_params.push(("service_settings_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.tenant {
                query_params.push(("tenant".to_string(), v.clone()));
            }
            if let Some(v) = &args.tenant_uuid {
                query_params.push(("tenant_uuid".to_string(), v.clone()));
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/openstack-subnets/",
                    &query_params,
                    args.limit,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        SubnetCommand::Get(args) => {
            let result = client
                .openstack_subnets_retrieve(args.uuid.as_str(), None)
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        SubnetCommand::Update(args) => {
            let result = client
                .openstack_subnets_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<
                        waldur_client::OpenStackSubNetRequest,
                    >(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        SubnetCommand::Delete(args) => {
            let _ = client.openstack_subnets_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
