//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "customer_name"];
///OpenStack tenants
#[derive(clap::Subcommand, Debug)]
pub enum TenantCommand {
    ///List openstack tenants
    List(TenantListArgs),
    ///Get openstack tenants
    Get(TenantGetArgs),
    ///Update openstack tenants
    Update(TenantUpdateArgs),
}
#[derive(clap::Args, Debug)]
pub struct TenantListArgs {
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["availability_zone",
            "backend_id",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_name",
            "customer_native_name",
            "customer_uuid",
            "default_volume_type_name",
            "description",
            "error_message",
            "error_traceback",
            "external_network_id",
            "external_network_ref_name",
            "external_network_ref_uuid",
            "internal_network_id",
            "is_limit_based",
            "is_usage_based",
            "marketplace_category_name",
            "marketplace_category_uuid",
            "marketplace_offering_name",
            "marketplace_offering_plugin_options",
            "marketplace_offering_type",
            "marketplace_offering_uuid",
            "marketplace_plan_uuid",
            "marketplace_resource_state",
            "marketplace_resource_uuid",
            "modified",
            "name",
            "project",
            "project_name",
            "project_uuid",
            "quotas",
            "resource_type",
            "security_groups",
            "service_name",
            "service_settings",
            "service_settings_error_message",
            "service_settings_state",
            "service_settings_uuid",
            "skip_creation_of_default_router",
            "skip_creation_of_default_subnet",
            "state",
            "subnet_cidr",
            "url",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct TenantGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct TenantUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: TenantCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        TenantCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.backend_id {
                query_params.push(("backend_id".to_string(), v.clone()));
            }
            if let Some(v) = args.can_manage {
                query_params.push(("can_manage".to_string(), v.to_string()));
            }
            if let Some(v) = &args.customer {
                query_params.push(("customer".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_abbreviation {
                query_params.push(("customer_abbreviation".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_name {
                query_params.push(("customer_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_native_name {
                query_params.push(("customer_native_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_uuid {
                query_params.push(("customer_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.description {
                query_params.push(("description".to_string(), v.clone()));
            }
            if let Some(v) = &args.external_ip {
                query_params.push(("external_ip".to_string(), v.clone()));
            }
            if let Some(v) = &args.name {
                query_params.push(("name".to_string(), v.clone()));
            }
            if let Some(v) = &args.name_exact {
                query_params.push(("name_exact".to_string(), v.clone()));
            }
            if let Some(v) = &args.project {
                query_params.push(("project".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_name {
                query_params.push(("project_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_uuid {
                query_params.push(("project_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.service_settings_name {
                query_params.push(("service_settings_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.service_settings_uuid {
                query_params.push(("service_settings_uuid".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/openstack-tenants/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        TenantCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-tenants/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        TenantCommand::Update(args) => {
            serde_json::from_str::<waldur_client::OpenStackTenantRequest>(&args.request)
                .with_context(|| {
                    format!(
                        "--{} is not valid JSON for the expected request body",
                        stringify!(request)
                    )
                })?;
            let path = format!("{}{}{}", "/api/openstack-tenants/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&args.request),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
