//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "size"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("attach_instance_uuid", crate::filter::FilterKind::Str),
    ("availability_zone_name", crate::filter::FilterKind::Str),
    ("backend_id", crate::filter::FilterKind::Str),
    ("can_manage", crate::filter::FilterKind::Bool),
    ("customer", crate::filter::FilterKind::Str),
    ("customer_abbreviation", crate::filter::FilterKind::Str),
    ("customer_name", crate::filter::FilterKind::Str),
    ("customer_native_name", crate::filter::FilterKind::Str),
    ("customer_uuid", crate::filter::FilterKind::Str),
    ("description", crate::filter::FilterKind::Str),
    ("external_ip", crate::filter::FilterKind::Str),
    ("instance", crate::filter::FilterKind::Str),
    ("instance_uuid", crate::filter::FilterKind::Str),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("project", crate::filter::FilterKind::Str),
    ("project_name", crate::filter::FilterKind::Str),
    ("project_uuid", crate::filter::FilterKind::Str),
    ("runtime_state", crate::filter::FilterKind::Str),
    ("service_settings_name", crate::filter::FilterKind::Str),
    ("service_settings_uuid", crate::filter::FilterKind::Str),
    ("snapshot", crate::filter::FilterKind::Str),
    ("snapshot_uuid", crate::filter::FilterKind::Str),
    ("state", crate::filter::FilterKind::Str),
    ("tenant", crate::filter::FilterKind::Str),
    ("tenant_uuid", crate::filter::FilterKind::Str),
];
const UPDATE_SKELETON: &str = "{\n  \"bootable\": null,\n  \"description\": null,\n  \"name\": \"\"\n}";
const PROVISION_SKELETON: &str = "{\n  \"accepting_terms_of_service\": true,\n  \"attributes\": {\n    \"availability_zone\": null,\n    \"description\": null,\n    \"image\": null,\n    \"name\": \"\",\n    \"size\": null,\n    \"type\": null\n  },\n  \"callback_url\": null,\n  \"limits\": null,\n  \"offering\": \"\",\n  \"plan\": null,\n  \"project\": \"\",\n  \"request_comment\": null,\n  \"slug\": null,\n  \"start_date\": null,\n  \"type\": null\n}";
///OpenStack volumes
#[derive(clap::Subcommand, Debug)]
pub enum VolumeCommand {
    ///List openstack volumes
    List(VolumeListArgs),
    ///Get openstack volumes
    Get(VolumeGetArgs),
    ///Update openstack volumes
    Update(VolumeUpdateArgs),
    ///Provision openstack volumes via a marketplace order
    Provision(VolumeProvisionArgs),
    ///Terminate openstack volumes via a marketplace order
    Terminate(VolumeTerminateArgs),
}
#[derive(clap::Args, Debug)]
pub struct VolumeListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["access_url",
            "action",
            "action_details",
            "availability_zone",
            "availability_zone_name",
            "backend_id",
            "bootable",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_name",
            "customer_native_name",
            "customer_uuid",
            "description",
            "device",
            "error_message",
            "error_traceback",
            "extend_enabled",
            "image",
            "image_metadata",
            "image_name",
            "instance",
            "instance_marketplace_uuid",
            "instance_name",
            "is_limit_based",
            "is_usage_based",
            "marketplace_category_name",
            "marketplace_category_uuid",
            "marketplace_offering_name",
            "marketplace_offering_plugin_options",
            "marketplace_offering_type",
            "marketplace_offering_uuid",
            "marketplace_plan_uuid",
            "marketplace_resource_state",
            "marketplace_resource_uuid",
            "metadata",
            "modified",
            "name",
            "project",
            "project_name",
            "project_uuid",
            "resource_type",
            "runtime_state",
            "service_name",
            "service_settings",
            "service_settings_error_message",
            "service_settings_state",
            "service_settings_uuid",
            "size",
            "source_snapshot",
            "state",
            "tenant",
            "tenant_uuid",
            "type",
            "type_name",
            "url",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct VolumeGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "volume_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct VolumeUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "volume_provision_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct VolumeProvisionArgs {
    /// The marketplace order body as inline JSON. Use
    /// --generate-skeleton for a template (offering/project plus
    /// this resource's typed attributes), or --request-file to
    /// read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the order body from a JSON or YAML file.
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable order template and exit, instead of
    /// submitting (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
    /// Submit the order and return immediately, without polling
    /// it to completion.
    #[arg(long)]
    pub no_wait: bool,
    /// Seconds to wait for the order to reach a terminal state
    /// before giving up (ignored with --no-wait).
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
}
#[derive(clap::Args, Debug)]
pub struct VolumeTerminateArgs {
    /// The marketplace resource UUID (a resource's
    /// `marketplace_resource_uuid` field, from get/list) -- not
    /// the plugin resource's own UUID.
    pub uuid: String,
    /// Optional termination attributes as inline JSON, e.g.
    /// '{"delete_volumes": true}'.
    #[arg(long)]
    pub request: Option<String>,
    /// Submit the termination and return immediately, without
    /// polling the order to completion.
    #[arg(long)]
    pub no_wait: bool,
    /// Seconds to wait for the termination order before giving
    /// up (ignored with --no-wait).
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    project: Option<&str>,
    dry_run: bool,
    command: VolumeCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        VolumeCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            if let Some(project) = project {
                if !query_params.iter().any(|(k, _)| k == "project_uuid") {
                    query_params.push(("project_uuid".to_string(), project.to_string()));
                }
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            if matches!(format, crate ::output::OutputFormat::Ndjson)
                && args.jmespath.is_none()
            {
                crate::pagination::fetch_all_streaming(
                        base_url,
                        token,
                        "/api/openstack-volumes/",
                        &query_params,
                        args.limit,
                        |item| crate::output::print_ndjson_line(&item),
                    )
                    .await?;
            } else {
                let result = crate::pagination::fetch_all(
                        base_url,
                        token,
                        "/api/openstack-volumes/",
                        &query_params,
                        args.limit,
                    )
                    .await?;
                let display_columns: Vec<&str> = match &args.fields {
                    Some(fields) => fields.iter().map(String::as_str).collect(),
                    None => COLUMNS.to_vec(),
                };
                let result: serde_json::Value = serde_json::Value::Array(result);
                let result = match &args.jmespath {
                    Some(expr) => crate::query::apply(result, expr)?,
                    None => result,
                };
                crate::output::print_result(&result, &display_columns, format)?;
            }
        }
        VolumeCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/openstack-volumes/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        VolumeCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::OpenStackVolumeRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/openstack-volumes/", uuid, "/");
            if dry_run {
                return crate::output::print_dry_run("PUT", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        VolumeCommand::Provision(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(PROVISION_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::order::provision(
                    base_url,
                    token,
                    &body,
                    project,
                    dry_run,
                    !args.no_wait,
                    args.timeout,
                    format,
                )
                .await?;
        }
        VolumeCommand::Terminate(args) => {
            crate::order::terminate(
                    base_url,
                    token,
                    &args.uuid,
                    args.request.as_deref(),
                    dry_run,
                    !args.no_wait,
                    args.timeout,
                    format,
                )
                .await?;
        }
    }
    Ok(())
}
