//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "state", "size"];
///OpenStack volumes
#[derive(clap::Subcommand, Debug)]
pub enum VolumeCommand {
    ///List openstack volumes
    List(VolumeListArgs),
    ///Get openstack volumes
    Get(VolumeGetArgs),
    ///Update openstack volumes
    Update(VolumeUpdateArgs),
}
#[derive(clap::Args, Debug)]
pub struct VolumeListArgs {
    #[arg(long)]
    pub attach_instance_uuid: Option<String>,
    #[arg(long)]
    pub availability_zone_name: Option<String>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub customer: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub external_ip: Option<String>,
    #[arg(long)]
    pub instance: Option<String>,
    #[arg(long)]
    pub instance_uuid: Option<String>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub project: Option<String>,
    #[arg(long)]
    pub project_name: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub runtime_state: Option<String>,
    #[arg(long)]
    pub service_settings_name: Option<String>,
    #[arg(long)]
    pub service_settings_uuid: Option<String>,
    #[arg(long)]
    pub snapshot: Option<String>,
    #[arg(long)]
    pub snapshot_uuid: Option<String>,
    #[arg(long)]
    pub tenant: Option<String>,
    #[arg(long)]
    pub tenant_uuid: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct VolumeGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct VolumeUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
pub async fn run(
    client: &HttpClient,
    command: VolumeCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        VolumeCommand::List(args) => {
            let result = client
                .openstack_volumes_list(
                    args.attach_instance_uuid.as_deref(),
                    args.availability_zone_name.as_deref(),
                    args.backend_id.as_deref(),
                    args.can_manage,
                    args.customer.as_deref(),
                    args.customer_abbreviation.as_deref(),
                    args.customer_name.as_deref(),
                    args.customer_native_name.as_deref(),
                    args.customer_uuid.as_deref(),
                    args.description.as_deref(),
                    args.external_ip.as_deref(),
                    None,
                    args.instance.as_deref(),
                    args.instance_uuid.as_deref(),
                    args.name.as_deref(),
                    args.name_exact.as_deref(),
                    args.page,
                    args.page_size,
                    args.project.as_deref(),
                    args.project_name.as_deref(),
                    args.project_uuid.as_deref(),
                    args.runtime_state.as_deref(),
                    args.service_settings_name.as_deref(),
                    args.service_settings_uuid.as_deref(),
                    args.snapshot.as_deref(),
                    args.snapshot_uuid.as_deref(),
                    None,
                    args.tenant.as_deref(),
                    args.tenant_uuid.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        VolumeCommand::Get(args) => {
            let result = client
                .openstack_volumes_retrieve(args.uuid.as_str(), None)
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        VolumeCommand::Update(args) => {
            let result = client
                .openstack_volumes_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<
                        waldur_client::OpenStackVolumeRequest,
                    >(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
