//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "abbreviation", "state"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("abbreviation", crate::filter::FilterKind::Str),
    ("accounting_is_running", crate::filter::FilterKind::Bool),
    ("agreement_number", crate::filter::FilterKind::Str),
    ("archived", crate::filter::FilterKind::Bool),
    ("backend_id", crate::filter::FilterKind::Str),
    ("contact_details", crate::filter::FilterKind::Str),
    ("current_user_has_project_create_permission", crate::filter::FilterKind::Bool),
    ("has_resources", crate::filter::FilterKind::Str),
    ("is_call_managing_organization", crate::filter::FilterKind::Bool),
    ("is_service_provider", crate::filter::FilterKind::Bool),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("native_name", crate::filter::FilterKind::Str),
    ("o", crate::filter::FilterKind::Str),
    ("organization_group_name", crate::filter::FilterKind::Str),
    ("organization_group_uuid", crate::filter::FilterKind::Str),
    ("owned_by_current_user", crate::filter::FilterKind::Bool),
    ("query", crate::filter::FilterKind::Str),
    ("registration_code", crate::filter::FilterKind::Str),
    ("service_provider_uuid", crate::filter::FilterKind::Str),
    ("slug", crate::filter::FilterKind::Str),
    ("user_uuid", crate::filter::FilterKind::Str),
];
const CREATE_SKELETON: &str = "{\n  \"abbreviation\": null,\n  \"access_subnets\": null,\n  \"accounting_start_date\": null,\n  \"address\": null,\n  \"agreement_number\": null,\n  \"apartment_nr\": null,\n  \"archived\": null,\n  \"backend_id\": null,\n  \"bank_account\": null,\n  \"bank_name\": null,\n  \"blocked\": null,\n  \"city\": null,\n  \"contact_details\": null,\n  \"country\": null,\n  \"default_tax_percent\": null,\n  \"description\": null,\n  \"display_billing_info_in_projects\": null,\n  \"domain\": null,\n  \"email\": null,\n  \"grace_period_days\": null,\n  \"homepage\": null,\n  \"house_nr\": null,\n  \"household\": null,\n  \"image\": null,\n  \"latitude\": null,\n  \"longitude\": null,\n  \"max_service_accounts\": null,\n  \"name\": \"\",\n  \"native_name\": null,\n  \"notification_emails\": null,\n  \"parish\": null,\n  \"phone_number\": null,\n  \"postal\": null,\n  \"project_metadata_checklist\": null,\n  \"project_slug_template\": null,\n  \"registration_code\": null,\n  \"slug\": null,\n  \"sponsor_number\": null,\n  \"state\": null,\n  \"street\": null,\n  \"user_affiliations\": null,\n  \"user_email_patterns\": null,\n  \"user_identity_sources\": null,\n  \"vat_code\": null\n}";
const UPDATE_SKELETON: &str = "{\n  \"abbreviation\": null,\n  \"access_subnets\": null,\n  \"accounting_start_date\": null,\n  \"address\": null,\n  \"agreement_number\": null,\n  \"apartment_nr\": null,\n  \"archived\": null,\n  \"backend_id\": null,\n  \"bank_account\": null,\n  \"bank_name\": null,\n  \"blocked\": null,\n  \"city\": null,\n  \"contact_details\": null,\n  \"country\": null,\n  \"default_tax_percent\": null,\n  \"description\": null,\n  \"display_billing_info_in_projects\": null,\n  \"domain\": null,\n  \"email\": null,\n  \"grace_period_days\": null,\n  \"homepage\": null,\n  \"house_nr\": null,\n  \"household\": null,\n  \"image\": null,\n  \"latitude\": null,\n  \"longitude\": null,\n  \"max_service_accounts\": null,\n  \"name\": \"\",\n  \"native_name\": null,\n  \"notification_emails\": null,\n  \"parish\": null,\n  \"phone_number\": null,\n  \"postal\": null,\n  \"project_metadata_checklist\": null,\n  \"project_slug_template\": null,\n  \"registration_code\": null,\n  \"slug\": null,\n  \"sponsor_number\": null,\n  \"state\": null,\n  \"street\": null,\n  \"user_affiliations\": null,\n  \"user_email_patterns\": null,\n  \"user_identity_sources\": null,\n  \"vat_code\": null\n}";
///Customers (organizations)
#[derive(clap::Subcommand, Debug)]
pub enum CustomerCommand {
    ///List customers (organizations)
    List(CustomerListArgs),
    ///Get customers (organizations)
    Get(CustomerGetArgs),
    ///Create customers (organizations)
    Create(CustomerCreateArgs),
    ///Update customers (organizations)
    Update(CustomerUpdateArgs),
    ///Delete customers (organizations)
    Delete(CustomerDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct CustomerListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["abbreviation",
            "access_subnets",
            "accounting_start_date",
            "address",
            "agreement_number",
            "apartment_nr",
            "archived",
            "backend_id",
            "bank_account",
            "bank_name",
            "billing_price_estimate",
            "blocked",
            "call_managing_organization_uuid",
            "city",
            "contact_details",
            "country",
            "country_name",
            "created",
            "customer_credit",
            "customer_unallocated_credit",
            "default_affiliations",
            "default_tax_percent",
            "description",
            "display_billing_info_in_projects",
            "display_name",
            "domain",
            "email",
            "grace_period_days",
            "homepage",
            "house_nr",
            "household",
            "image",
            "is_service_provider",
            "latitude",
            "longitude",
            "max_service_accounts",
            "name",
            "native_name",
            "notification_emails",
            "organization_groups",
            "parish",
            "payment_profiles",
            "phone_number",
            "postal",
            "project_metadata_checklist",
            "project_slug_template",
            "projects_count",
            "registration_code",
            "service_provider",
            "service_provider_uuid",
            "slug",
            "sponsor_number",
            "state",
            "street",
            "url",
            "user_affiliations",
            "user_email_patterns",
            "user_identity_sources",
            "users_count",
            "uuid",
            "vat_code"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "customer_create_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct CustomerCreateArgs {
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "customer_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct CustomerUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    _project: Option<&str>,
    command: CustomerCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        CustomerCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/customers/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            let result: serde_json::Value = serde_json::Value::Array(result);
            let result = match &args.jmespath {
                Some(expr) => crate::query::apply(result, expr)?,
                None => result,
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        CustomerCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/customers/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Create(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::CustomerRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let path = "/api/customers/".to_string();
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::CustomerRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/customers/", uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Delete(args) => {
            let path = format!("{}{}{}", "/api/customers/", args.uuid, "/");
            let _ = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::DELETE,
                    &path,
                    None,
                )
                .await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
