//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "abbreviation", "state"];
const CREATE_SKELETON: &str = "{\n  \"abbreviation\": null,\n  \"access_subnets\": null,\n  \"accounting_start_date\": null,\n  \"address\": null,\n  \"agreement_number\": null,\n  \"apartment_nr\": null,\n  \"archived\": null,\n  \"backend_id\": null,\n  \"bank_account\": null,\n  \"bank_name\": null,\n  \"blocked\": null,\n  \"city\": null,\n  \"contact_details\": null,\n  \"country\": null,\n  \"default_tax_percent\": null,\n  \"description\": null,\n  \"display_billing_info_in_projects\": null,\n  \"domain\": null,\n  \"email\": null,\n  \"grace_period_days\": null,\n  \"homepage\": null,\n  \"house_nr\": null,\n  \"household\": null,\n  \"image\": null,\n  \"latitude\": null,\n  \"longitude\": null,\n  \"max_service_accounts\": null,\n  \"name\": \"\",\n  \"native_name\": null,\n  \"notification_emails\": null,\n  \"parish\": null,\n  \"phone_number\": null,\n  \"postal\": null,\n  \"project_metadata_checklist\": null,\n  \"project_slug_template\": null,\n  \"registration_code\": null,\n  \"slug\": null,\n  \"sponsor_number\": null,\n  \"state\": null,\n  \"street\": null,\n  \"user_affiliations\": null,\n  \"user_email_patterns\": null,\n  \"user_identity_sources\": null,\n  \"vat_code\": null\n}";
const UPDATE_SKELETON: &str = "{\n  \"abbreviation\": null,\n  \"access_subnets\": null,\n  \"accounting_start_date\": null,\n  \"address\": null,\n  \"agreement_number\": null,\n  \"apartment_nr\": null,\n  \"archived\": null,\n  \"backend_id\": null,\n  \"bank_account\": null,\n  \"bank_name\": null,\n  \"blocked\": null,\n  \"city\": null,\n  \"contact_details\": null,\n  \"country\": null,\n  \"default_tax_percent\": null,\n  \"description\": null,\n  \"display_billing_info_in_projects\": null,\n  \"domain\": null,\n  \"email\": null,\n  \"grace_period_days\": null,\n  \"homepage\": null,\n  \"house_nr\": null,\n  \"household\": null,\n  \"image\": null,\n  \"latitude\": null,\n  \"longitude\": null,\n  \"max_service_accounts\": null,\n  \"name\": \"\",\n  \"native_name\": null,\n  \"notification_emails\": null,\n  \"parish\": null,\n  \"phone_number\": null,\n  \"postal\": null,\n  \"project_metadata_checklist\": null,\n  \"project_slug_template\": null,\n  \"registration_code\": null,\n  \"slug\": null,\n  \"sponsor_number\": null,\n  \"state\": null,\n  \"street\": null,\n  \"user_affiliations\": null,\n  \"user_email_patterns\": null,\n  \"user_identity_sources\": null,\n  \"vat_code\": null\n}";
///Customers (organizations)
#[derive(clap::Subcommand, Debug)]
pub enum CustomerCommand {
    ///List customers (organizations)
    List(CustomerListArgs),
    ///Get customers (organizations)
    Get(CustomerGetArgs),
    ///Create customers (organizations)
    Create(CustomerCreateArgs),
    ///Update customers (organizations)
    Update(CustomerUpdateArgs),
    ///Delete customers (organizations)
    Delete(CustomerDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct CustomerListArgs {
    #[arg(long)]
    pub abbreviation: Option<String>,
    #[arg(long)]
    pub accounting_is_running: Option<bool>,
    #[arg(long)]
    pub agreement_number: Option<String>,
    #[arg(long)]
    pub archived: Option<bool>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub contact_details: Option<String>,
    #[arg(long)]
    pub current_user_has_project_create_permission: Option<bool>,
    #[arg(long)]
    pub has_resources: Option<String>,
    #[arg(long)]
    pub is_call_managing_organization: Option<bool>,
    #[arg(long)]
    pub is_service_provider: Option<bool>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub native_name: Option<String>,
    #[arg(long)]
    pub o: Option<String>,
    #[arg(long)]
    pub organization_group_name: Option<String>,
    #[arg(long)]
    pub owned_by_current_user: Option<bool>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub registration_code: Option<String>,
    #[arg(long)]
    pub service_provider_uuid: Option<String>,
    #[arg(long)]
    pub slug: Option<String>,
    #[arg(long)]
    pub user_uuid: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["abbreviation",
            "access_subnets",
            "accounting_start_date",
            "address",
            "agreement_number",
            "apartment_nr",
            "archived",
            "backend_id",
            "bank_account",
            "bank_name",
            "billing_price_estimate",
            "blocked",
            "call_managing_organization_uuid",
            "city",
            "contact_details",
            "country",
            "country_name",
            "created",
            "customer_credit",
            "customer_unallocated_credit",
            "default_affiliations",
            "default_tax_percent",
            "description",
            "display_billing_info_in_projects",
            "display_name",
            "domain",
            "email",
            "grace_period_days",
            "has_affiliate_links",
            "homepage",
            "house_nr",
            "household",
            "image",
            "is_service_provider",
            "latitude",
            "longitude",
            "max_service_accounts",
            "name",
            "native_name",
            "notification_emails",
            "organization_groups",
            "parish",
            "payment_profiles",
            "phone_number",
            "postal",
            "project_metadata_checklist",
            "project_slug_template",
            "projects_count",
            "registration_code",
            "service_provider",
            "service_provider_uuid",
            "slug",
            "sponsor_number",
            "state",
            "street",
            "url",
            "user_affiliations",
            "user_email_patterns",
            "user_identity_sources",
            "users_count",
            "uuid",
            "vat_code"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "customer_create_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct CustomerCreateArgs {
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "customer_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct CustomerUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: CustomerCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        CustomerCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.abbreviation {
                query_params.push(("abbreviation".to_string(), v.clone()));
            }
            if let Some(v) = args.accounting_is_running {
                query_params.push(("accounting_is_running".to_string(), v.to_string()));
            }
            if let Some(v) = &args.agreement_number {
                query_params.push(("agreement_number".to_string(), v.clone()));
            }
            if let Some(v) = args.archived {
                query_params.push(("archived".to_string(), v.to_string()));
            }
            if let Some(v) = &args.backend_id {
                query_params.push(("backend_id".to_string(), v.clone()));
            }
            if let Some(v) = &args.contact_details {
                query_params.push(("contact_details".to_string(), v.clone()));
            }
            if let Some(v) = args.current_user_has_project_create_permission {
                query_params
                    .push((
                        "current_user_has_project_create_permission".to_string(),
                        v.to_string(),
                    ));
            }
            if let Some(v) = &args.has_resources {
                query_params.push(("has_resources".to_string(), v.clone()));
            }
            if let Some(v) = args.is_call_managing_organization {
                query_params
                    .push(("is_call_managing_organization".to_string(), v.to_string()));
            }
            if let Some(v) = args.is_service_provider {
                query_params.push(("is_service_provider".to_string(), v.to_string()));
            }
            if let Some(v) = &args.name {
                query_params.push(("name".to_string(), v.clone()));
            }
            if let Some(v) = &args.name_exact {
                query_params.push(("name_exact".to_string(), v.clone()));
            }
            if let Some(v) = &args.native_name {
                query_params.push(("native_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.o {
                query_params.push(("o".to_string(), v.clone()));
            }
            if let Some(v) = &args.organization_group_name {
                query_params.push(("organization_group_name".to_string(), v.clone()));
            }
            if let Some(v) = args.owned_by_current_user {
                query_params.push(("owned_by_current_user".to_string(), v.to_string()));
            }
            if let Some(v) = &args.query {
                query_params.push(("query".to_string(), v.clone()));
            }
            if let Some(v) = &args.registration_code {
                query_params.push(("registration_code".to_string(), v.clone()));
            }
            if let Some(v) = &args.service_provider_uuid {
                query_params.push(("service_provider_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.slug {
                query_params.push(("slug".to_string(), v.clone()));
            }
            if let Some(v) = &args.user_uuid {
                query_params.push(("user_uuid".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/customers/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        CustomerCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/customers/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Create(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::CustomerRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let path = "/api/customers/".to_string();
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::CustomerRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/customers/", uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Delete(args) => {
            let path = format!("{}{}{}", "/api/customers/", args.uuid, "/");
            let _ = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::DELETE,
                    &path,
                    None,
                )
                .await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
