//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
const COLUMNS: &[&str; 3usize] = &["uuid", "customer_name", "is_pending"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("closed", crate::filter::FilterKind::Str),
    ("customer_uuid", crate::filter::FilterKind::Str),
    ("is_pending", crate::filter::FilterKind::Bool),
    ("o", crate::filter::FilterKind::Str),
    ("reviewer_uuid", crate::filter::FilterKind::Str),
];
///Customer permission reviews (read-only)
#[derive(clap::Subcommand, Debug)]
pub enum CustomerPermissionsReviewCommand {
    ///List customer permission reviews (read-only)
    List(CustomerPermissionsReviewListArgs),
    ///Get customer permission reviews (read-only)
    Get(CustomerPermissionsReviewGetArgs),
}
#[derive(clap::Args, Debug)]
pub struct CustomerPermissionsReviewListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(long, value_delimiter = ',')]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerPermissionsReviewGetArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: CustomerPermissionsReviewCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        CustomerPermissionsReviewCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/customer-permissions-reviews/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            let result: serde_json::Value = serde_json::Value::Array(result);
            let result = match &args.jmespath {
                Some(expr) => crate::query::apply(result, expr)?,
                None => result,
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        CustomerPermissionsReviewCommand::Get(args) => {
            let path = format!(
                "{}{}{}", "/api/customer-permissions-reviews/", args.uuid, "/"
            );
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
