//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use waldur_client::HttpClient;
const COLUMNS: &[&str; 3usize] = &["uuid", "customer_name", "is_pending"];
///Customer permission reviews (read-only)
#[derive(clap::Subcommand, Debug)]
pub enum CustomerPermissionsReviewCommand {
    ///List customer permission reviews (read-only)
    List(CustomerPermissionsReviewListArgs),
    ///Get customer permission reviews (read-only)
    Get(CustomerPermissionsReviewGetArgs),
}
#[derive(clap::Args, Debug)]
pub struct CustomerPermissionsReviewListArgs {
    #[arg(long)]
    pub closed: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub is_pending: Option<bool>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub reviewer_uuid: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerPermissionsReviewGetArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: CustomerPermissionsReviewCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        CustomerPermissionsReviewCommand::List(args) => {
            let result = client
                .customer_permissions_reviews_list(
                    args.closed.as_deref(),
                    args.customer_uuid.as_deref(),
                    args.is_pending,
                    None,
                    args.page,
                    args.page_size,
                    args.reviewer_uuid.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerPermissionsReviewCommand::Get(args) => {
            let result = client
                .customer_permissions_reviews_retrieve(args.uuid.as_str())
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
