//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "abbreviation", "state"];
///Customers (organizations)
#[derive(clap::Subcommand, Debug)]
pub enum CustomerCommand {
    ///List customers (organizations)
    List(CustomerListArgs),
    ///Get customers (organizations)
    Get(CustomerGetArgs),
    ///Create customers (organizations)
    Create(CustomerCreateArgs),
    ///Update customers (organizations)
    Update(CustomerUpdateArgs),
    ///Delete customers (organizations)
    Delete(CustomerDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct CustomerListArgs {
    #[arg(long)]
    pub abbreviation: Option<String>,
    #[arg(long)]
    pub accounting_is_running: Option<bool>,
    #[arg(long)]
    pub agreement_number: Option<String>,
    #[arg(long)]
    pub archived: Option<bool>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub contact_details: Option<String>,
    #[arg(long)]
    pub current_user_has_project_create_permission: Option<bool>,
    #[arg(long)]
    pub has_resources: Option<String>,
    #[arg(long)]
    pub is_call_managing_organization: Option<bool>,
    #[arg(long)]
    pub is_service_provider: Option<bool>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub native_name: Option<String>,
    #[arg(long)]
    pub o: Option<String>,
    #[arg(long)]
    pub organization_group_name: Option<String>,
    #[arg(long)]
    pub owned_by_current_user: Option<bool>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub registration_code: Option<String>,
    #[arg(long)]
    pub service_provider_uuid: Option<String>,
    #[arg(long)]
    pub slug: Option<String>,
    #[arg(long)]
    pub user_uuid: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct CustomerCreateArgs {
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct CustomerUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct CustomerDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: CustomerCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        CustomerCommand::List(args) => {
            let result = client
                .customers_list(
                    args.abbreviation.as_deref(),
                    args.accounting_is_running,
                    args.agreement_number.as_deref(),
                    args.archived,
                    args.backend_id.as_deref(),
                    args.contact_details.as_deref(),
                    args.current_user_has_project_create_permission,
                    None,
                    None,
                    args.has_resources.as_deref(),
                    args.is_call_managing_organization,
                    args.is_service_provider,
                    args.name.as_deref(),
                    args.name_exact.as_deref(),
                    args.native_name.as_deref(),
                    args.o.as_deref(),
                    args.organization_group_name.as_deref(),
                    None,
                    args.owned_by_current_user,
                    args.page,
                    args.page_size,
                    args.query.as_deref(),
                    args.registration_code.as_deref(),
                    args.service_provider_uuid.as_deref(),
                    args.slug.as_deref(),
                    args.user_uuid.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Get(args) => {
            let result = client.customers_retrieve(args.uuid.as_str(), None).await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Create(args) => {
            let result = client
                .customers_create(
                    serde_json::from_str::<waldur_client::CustomerRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Update(args) => {
            let result = client
                .customers_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<waldur_client::CustomerRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        CustomerCommand::Delete(args) => {
            let _ = client.customers_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
            }
        }
    }
    Ok(())
}
