//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use waldur_client::HttpClient;
const COLUMNS: &[&str; 3usize] = &["uuid", "customer_name", "is_pending"];
///Customer permission reviews (read-only)
#[derive(clap::Subcommand, Debug)]
pub enum CustomerPermissionsReviewCommand {
    ///List customer permission reviews (read-only)
    List(CustomerPermissionsReviewListArgs),
    ///Get customer permission reviews (read-only)
    Get(CustomerPermissionsReviewGetArgs),
}
#[derive(clap::Args, Debug)]
pub struct CustomerPermissionsReviewListArgs {
    #[arg(long)]
    pub closed: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub is_pending: Option<bool>,
    #[arg(long)]
    pub reviewer_uuid: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(long, value_delimiter = ',')]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct CustomerPermissionsReviewGetArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: CustomerPermissionsReviewCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        CustomerPermissionsReviewCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.closed {
                query_params.push(("closed".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_uuid {
                query_params.push(("customer_uuid".to_string(), v.clone()));
            }
            if let Some(v) = args.is_pending {
                query_params.push(("is_pending".to_string(), v.to_string()));
            }
            if let Some(v) = &args.reviewer_uuid {
                query_params.push(("reviewer_uuid".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/customer-permissions-reviews/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        CustomerPermissionsReviewCommand::Get(args) => {
            let result = client
                .customer_permissions_reviews_retrieve(args.uuid.as_str())
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
