//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 3usize] = &["uuid", "name", "parent_uuid"];
///Organization groups
#[derive(clap::Subcommand, Debug)]
pub enum OrganizationGroupCommand {
    ///List organization groups
    List(OrganizationGroupListArgs),
    ///Get organization groups
    Get(OrganizationGroupGetArgs),
    ///Create organization groups
    Create(OrganizationGroupCreateArgs),
    ///Update organization groups
    Update(OrganizationGroupUpdateArgs),
    ///Delete organization groups
    Delete(OrganizationGroupDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct OrganizationGroupListArgs {
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub o: Option<String>,
    #[arg(long)]
    pub parent: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(long, value_delimiter = ',')]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct OrganizationGroupGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct OrganizationGroupCreateArgs {
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct OrganizationGroupUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct OrganizationGroupDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: OrganizationGroupCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        OrganizationGroupCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.name {
                query_params.push(("name".to_string(), v.clone()));
            }
            if let Some(v) = &args.name_exact {
                query_params.push(("name_exact".to_string(), v.clone()));
            }
            if let Some(v) = &args.o {
                query_params.push(("o".to_string(), v.clone()));
            }
            if let Some(v) = &args.parent {
                query_params.push(("parent".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/organization-groups/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        OrganizationGroupCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/organization-groups/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        OrganizationGroupCommand::Create(args) => {
            serde_json::from_str::<
                waldur_client::OrganizationGroupRequest,
            >(&args.request)
                .with_context(|| {
                    format!(
                        "--{} is not valid JSON for the expected request body",
                        stringify!(request)
                    )
                })?;
            let path = "/api/organization-groups/".to_string();
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&args.request),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        OrganizationGroupCommand::Update(args) => {
            serde_json::from_str::<
                waldur_client::OrganizationGroupRequest,
            >(&args.request)
                .with_context(|| {
                    format!(
                        "--{} is not valid JSON for the expected request body",
                        stringify!(request)
                    )
                })?;
            let path = format!("{}{}{}", "/api/organization-groups/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&args.request),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        OrganizationGroupCommand::Delete(args) => {
            let path = format!("{}{}{}", "/api/organization-groups/", args.uuid, "/");
            let _ = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::DELETE,
                    &path,
                    None,
                )
                .await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
