//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
const COLUMNS: &[&str; 5usize] = &[
    "uuid",
    "name",
    "token_prefix",
    "expires_at",
    "is_active",
];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[];
const CREATE_SKELETON: &str = "{\n  \"allowed_scopes\": null,\n  \"expires_at\": \"\",\n  \"name\": \"\",\n  \"scopes\": [\n    \"\"\n  ]\n}";
const CREATE_REQUEST_SCHEMA: &str = "{\"properties\":{\"allowed_scopes\":{\"items\":{\"properties\":{\"type\":{\"type\":\"string\"},\"uuid\":{\"format\":\"uuid\",\"type\":\"string\"}},\"required\":[\"type\",\"uuid\"],\"type\":\"object\"},\"type\":\"array\"},\"expires_at\":{\"format\":\"date-time\",\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"scopes\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}},\"required\":[\"expires_at\",\"name\",\"scopes\"],\"type\":\"object\"}";
///Personal access tokens (named, scoped, time-limited API credentials)
#[derive(clap::Subcommand, Debug)]
pub enum PersonalAccessTokenCommand {
    ///List personal access tokens (named, scoped, time-limited api credentials)
    List(PersonalAccessTokenListArgs),
    ///Get personal access tokens (named, scoped, time-limited api credentials)
    Get(PersonalAccessTokenGetArgs),
    ///Create personal access tokens (named, scoped, time-limited api credentials)
    Create(PersonalAccessTokenCreateArgs),
    ///Delete personal access tokens (named, scoped, time-limited api credentials)
    Delete(PersonalAccessTokenDeleteArgs),
    ///Wait for a --jmespath condition on personal access tokens (named, scoped, time-limited api credentials)
    Wait(PersonalAccessTokenWaitArgs),
    ///Rotate personal access tokens (named, scoped, time-limited api credentials)
    Rotate(PersonalAccessTokenRotateArgs),
}
#[derive(clap::Args, Debug)]
pub struct PersonalAccessTokenListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(long, value_delimiter = ',')]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct PersonalAccessTokenGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "personal_access_token_create_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct PersonalAccessTokenCreateArgs {
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct PersonalAccessTokenDeleteArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct PersonalAccessTokenWaitArgs {
    pub uuid: String,
    /// JMESPath condition to poll for, evaluated against the
    /// fetched object on every poll (e.g. "state=='OK'").
    /// Waiting stops as soon as this evaluates to anything
    /// other than false or null.
    #[arg(long)]
    pub jmespath: String,
    /// Seconds to wait for the condition before giving up.
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
    /// Seconds between polls.
    #[arg(long, default_value_t = 3)]
    pub interval: u64,
}
#[derive(clap::Args, Debug)]
pub struct PersonalAccessTokenRotateArgs {
    pub uuid: String,
}
pub async fn run(
    base_url: &str,
    token: Option<&str>,
    _project: Option<&str>,
    dry_run: bool,
    command: PersonalAccessTokenCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        PersonalAccessTokenCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            if matches!(format, crate ::output::OutputFormat::Ndjson)
                && args.jmespath.is_none()
            {
                crate::pagination::fetch_all_streaming(
                        base_url,
                        token,
                        "/api/personal-access-tokens/",
                        &query_params,
                        args.limit,
                        |item| crate::output::print_ndjson_line(&item),
                    )
                    .await?;
            } else {
                let result = crate::pagination::fetch_all(
                        base_url,
                        token,
                        "/api/personal-access-tokens/",
                        &query_params,
                        args.limit,
                    )
                    .await?;
                let display_columns: Vec<&str> = match &args.fields {
                    Some(fields) => fields.iter().map(String::as_str).collect(),
                    None => COLUMNS.to_vec(),
                };
                let result: serde_json::Value = serde_json::Value::Array(result);
                let result = match &args.jmespath {
                    Some(expr) => crate::query::apply(result, expr)?,
                    None => result,
                };
                crate::output::print_result(&result, &display_columns, format)?;
            }
        }
        PersonalAccessTokenCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/personal-access-tokens/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        PersonalAccessTokenCommand::Create(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            crate::request::validate_request_body(CREATE_REQUEST_SCHEMA, &body)?;
            let path = "/api/personal-access-tokens/".to_string();
            if dry_run {
                return crate::output::print_dry_run("POST", &path, Some(&body), format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        PersonalAccessTokenCommand::Delete(args) => {
            let path = format!("{}{}{}", "/api/personal-access-tokens/", args.uuid, "/");
            if dry_run {
                return crate::output::print_dry_run("DELETE", &path, None, format);
            }
            let _ = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::DELETE,
                    &path,
                    None,
                )
                .await?;
            match format {
                crate::output::OutputFormat::Json
                | crate::output::OutputFormat::Ndjson => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
        PersonalAccessTokenCommand::Wait(args) => {
            let path = format!("{}{}{}", "/api/personal-access-tokens/", args.uuid, "/");
            crate::wait::wait_for(
                    base_url,
                    token,
                    &path,
                    &args.jmespath,
                    args.timeout,
                    args.interval,
                    COLUMNS,
                    format,
                )
                .await?;
        }
        PersonalAccessTokenCommand::Rotate(args) => {
            let path = format!(
                "{}{}{}", "/api/personal-access-tokens/", args.uuid, "/rotate/"
            );
            if dry_run {
                return crate::output::print_dry_run("POST", &path, None, format);
            }
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
