//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "customer_name", "description"];
///Projects
#[derive(clap::Subcommand, Debug)]
pub enum ProjectCommand {
    ///List projects
    List(ProjectListArgs),
    ///Get projects
    Get(ProjectGetArgs),
    ///Create projects
    Create(ProjectCreateArgs),
    ///Update projects
    Update(ProjectUpdateArgs),
    ///Delete projects
    Delete(ProjectDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct ProjectListArgs {
    #[arg(long)]
    pub accounting_is_running: Option<bool>,
    #[arg(long)]
    pub affiliation_name: Option<String>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_admin: Option<bool>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub conceal_finished_projects: Option<bool>,
    #[arg(long)]
    pub created: Option<String>,
    #[arg(long)]
    pub created_before: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub has_affiliation: Option<bool>,
    #[arg(long)]
    pub include_terminated: Option<bool>,
    #[arg(long)]
    pub is_removed: Option<bool>,
    #[arg(long)]
    pub modified: Option<String>,
    #[arg(long)]
    pub modified_before: Option<String>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub science_domain_uuid: Option<String>,
    #[arg(long)]
    pub science_sub_domain_uuid: Option<String>,
    #[arg(long)]
    pub slug: Option<String>,
    #[arg(long)]
    pub user_uuid: Option<String>,
    #[arg(long)]
    pub user_uuid_with_active_role: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["affiliation",
            "affiliation_code",
            "affiliation_name",
            "affiliation_uuid",
            "backend_id",
            "billing_price_estimate",
            "created",
            "customer",
            "customer_abbreviation",
            "customer_display_billing_info_in_projects",
            "customer_grace_period_days",
            "customer_name",
            "customer_native_name",
            "customer_slug",
            "customer_uuid",
            "description",
            "effective_end_date",
            "end_date",
            "end_date_requested_by",
            "end_date_updated_at",
            "grace_period_days",
            "image",
            "is_in_grace_period",
            "is_industry",
            "is_removed",
            "kind",
            "marketplace_resource_count",
            "max_service_accounts",
            "name",
            "oecd_fos_2007_code",
            "oecd_fos_2007_label",
            "project_credit",
            "project_metadata",
            "resources_count",
            "science_domain_code",
            "science_domain_name",
            "science_domain_uuid",
            "science_sub_domain",
            "science_sub_domain_code",
            "science_sub_domain_name",
            "slug",
            "staff_notes",
            "start_date",
            "termination_metadata",
            "type",
            "type_name",
            "type_uuid",
            "url",
            "user_affiliations",
            "user_email_patterns",
            "user_identity_sources",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct ProjectGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct ProjectCreateArgs {
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct ProjectUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct ProjectDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: ProjectCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        ProjectCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = args.accounting_is_running {
                query_params.push(("accounting_is_running".to_string(), v.to_string()));
            }
            if let Some(v) = &args.affiliation_name {
                query_params.push(("affiliation_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.backend_id {
                query_params.push(("backend_id".to_string(), v.clone()));
            }
            if let Some(v) = args.can_admin {
                query_params.push(("can_admin".to_string(), v.to_string()));
            }
            if let Some(v) = args.can_manage {
                query_params.push(("can_manage".to_string(), v.to_string()));
            }
            if let Some(v) = args.conceal_finished_projects {
                query_params
                    .push(("conceal_finished_projects".to_string(), v.to_string()));
            }
            if let Some(v) = &args.created {
                query_params.push(("created".to_string(), v.clone()));
            }
            if let Some(v) = &args.created_before {
                query_params.push(("created_before".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_abbreviation {
                query_params.push(("customer_abbreviation".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_name {
                query_params.push(("customer_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_native_name {
                query_params.push(("customer_native_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.description {
                query_params.push(("description".to_string(), v.clone()));
            }
            if let Some(v) = args.has_affiliation {
                query_params.push(("has_affiliation".to_string(), v.to_string()));
            }
            if let Some(v) = args.include_terminated {
                query_params.push(("include_terminated".to_string(), v.to_string()));
            }
            if let Some(v) = args.is_removed {
                query_params.push(("is_removed".to_string(), v.to_string()));
            }
            if let Some(v) = &args.modified {
                query_params.push(("modified".to_string(), v.clone()));
            }
            if let Some(v) = &args.modified_before {
                query_params.push(("modified_before".to_string(), v.clone()));
            }
            if let Some(v) = &args.name {
                query_params.push(("name".to_string(), v.clone()));
            }
            if let Some(v) = &args.name_exact {
                query_params.push(("name_exact".to_string(), v.clone()));
            }
            if let Some(v) = &args.query {
                query_params.push(("query".to_string(), v.clone()));
            }
            if let Some(v) = &args.science_domain_uuid {
                query_params.push(("science_domain_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.science_sub_domain_uuid {
                query_params.push(("science_sub_domain_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.slug {
                query_params.push(("slug".to_string(), v.clone()));
            }
            if let Some(v) = &args.user_uuid {
                query_params.push(("user_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.user_uuid_with_active_role {
                query_params.push(("user_uuid_with_active_role".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/projects/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        ProjectCommand::Get(args) => {
            let result = client.projects_retrieve(args.uuid.as_str(), None).await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        ProjectCommand::Create(args) => {
            let result = client
                .projects_create(
                    serde_json::from_str::<waldur_client::ProjectRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        ProjectCommand::Update(args) => {
            let result = client
                .projects_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<waldur_client::ProjectRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        ProjectCommand::Delete(args) => {
            let _ = client.projects_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
