//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "customer_name", "description"];
///Projects
#[derive(clap::Subcommand, Debug)]
pub enum ProjectCommand {
    ///List projects
    List(ProjectListArgs),
    ///Get projects
    Get(ProjectGetArgs),
    ///Create projects
    Create(ProjectCreateArgs),
    ///Update projects
    Update(ProjectUpdateArgs),
    ///Delete projects
    Delete(ProjectDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct ProjectListArgs {
    #[arg(long)]
    pub accounting_is_running: Option<bool>,
    #[arg(long)]
    pub affiliation_name: Option<String>,
    #[arg(long)]
    pub backend_id: Option<String>,
    #[arg(long)]
    pub can_admin: Option<bool>,
    #[arg(long)]
    pub can_manage: Option<bool>,
    #[arg(long)]
    pub conceal_finished_projects: Option<bool>,
    #[arg(long)]
    pub created: Option<String>,
    #[arg(long)]
    pub created_before: Option<String>,
    #[arg(long)]
    pub customer_abbreviation: Option<String>,
    #[arg(long)]
    pub customer_name: Option<String>,
    #[arg(long)]
    pub customer_native_name: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub has_affiliation: Option<bool>,
    #[arg(long)]
    pub include_terminated: Option<bool>,
    #[arg(long)]
    pub is_removed: Option<bool>,
    #[arg(long)]
    pub modified: Option<String>,
    #[arg(long)]
    pub modified_before: Option<String>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub name_exact: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub science_domain_uuid: Option<String>,
    #[arg(long)]
    pub science_sub_domain_uuid: Option<String>,
    #[arg(long)]
    pub slug: Option<String>,
    #[arg(long)]
    pub user_uuid: Option<String>,
    #[arg(long)]
    pub user_uuid_with_active_role: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct ProjectGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct ProjectCreateArgs {
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct ProjectUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct ProjectDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: ProjectCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        ProjectCommand::List(args) => {
            let result = client
                .projects_list(
                    args.accounting_is_running,
                    args.affiliation_name.as_deref(),
                    None,
                    args.backend_id.as_deref(),
                    args.can_admin,
                    args.can_manage,
                    args.conceal_finished_projects,
                    args.created.as_deref(),
                    args.created_before.as_deref(),
                    None,
                    args.customer_abbreviation.as_deref(),
                    args.customer_name.as_deref(),
                    args.customer_native_name.as_deref(),
                    args.description.as_deref(),
                    None,
                    args.has_affiliation,
                    args.include_terminated,
                    args.is_removed,
                    args.modified.as_deref(),
                    args.modified_before.as_deref(),
                    args.name.as_deref(),
                    args.name_exact.as_deref(),
                    None,
                    args.page,
                    args.page_size,
                    args.query.as_deref(),
                    args.science_domain_uuid.as_deref(),
                    args.science_sub_domain_uuid.as_deref(),
                    args.slug.as_deref(),
                    args.user_uuid.as_deref(),
                    args.user_uuid_with_active_role.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        ProjectCommand::Get(args) => {
            let result = client.projects_retrieve(args.uuid.as_str(), None).await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        ProjectCommand::Create(args) => {
            let result = client
                .projects_create(
                    serde_json::from_str::<waldur_client::ProjectRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        ProjectCommand::Update(args) => {
            let result = client
                .projects_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<waldur_client::ProjectRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        ProjectCommand::Delete(args) => {
            let _ = client.projects_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
            }
        }
    }
    Ok(())
}
