//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 3usize] = &["uuid", "name", "description"];
const CREATE_SKELETON: &str = "{\n  \"content_type\": \"\",\n  \"description\": null,\n  \"description_ar\": null,\n  \"description_cs\": null,\n  \"description_da\": null,\n  \"description_de\": null,\n  \"description_en\": null,\n  \"description_es\": null,\n  \"description_et\": null,\n  \"description_fr\": null,\n  \"description_it\": null,\n  \"description_lt\": null,\n  \"description_lv\": null,\n  \"description_nb\": null,\n  \"description_ru\": null,\n  \"description_sv\": null,\n  \"is_active\": null,\n  \"name\": \"\",\n  \"permissions\": {}\n}";
const UPDATE_SKELETON: &str = "{\n  \"content_type\": \"\",\n  \"description\": null,\n  \"description_ar\": null,\n  \"description_cs\": null,\n  \"description_da\": null,\n  \"description_de\": null,\n  \"description_en\": null,\n  \"description_es\": null,\n  \"description_et\": null,\n  \"description_fr\": null,\n  \"description_it\": null,\n  \"description_lt\": null,\n  \"description_lv\": null,\n  \"description_nb\": null,\n  \"description_ru\": null,\n  \"description_sv\": null,\n  \"is_active\": null,\n  \"name\": \"\",\n  \"permissions\": {}\n}";
///Roles
#[derive(clap::Subcommand, Debug)]
pub enum RoleCommand {
    ///List roles
    List(RoleListArgs),
    ///Get roles
    Get(RoleGetArgs),
    ///Create roles
    Create(RoleCreateArgs),
    ///Update roles
    Update(RoleUpdateArgs),
    ///Delete roles
    Delete(RoleDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct RoleListArgs {
    #[arg(long)]
    pub available_for_customer: Option<String>,
    #[arg(long)]
    pub content_type: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub include_concealed: Option<bool>,
    #[arg(long)]
    pub is_active: Option<bool>,
    #[arg(long)]
    pub is_system_role: Option<bool>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub query: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["content_type",
            "customer_name",
            "customer_uuid",
            "description",
            "description_ar",
            "description_cs",
            "description_da",
            "description_de",
            "description_en",
            "description_es",
            "description_et",
            "description_fr",
            "description_it",
            "description_lt",
            "description_lv",
            "description_nb",
            "description_ru",
            "description_sv",
            "is_active",
            "is_system_role",
            "name",
            "permissions",
            "template_name",
            "template_uuid",
            "users_count",
            "uuid"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct RoleGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "role_create_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct RoleCreateArgs {
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "role_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct RoleUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct RoleDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: RoleCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        RoleCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.available_for_customer {
                query_params.push(("available_for_customer".to_string(), v.clone()));
            }
            if let Some(v) = &args.content_type {
                query_params.push(("content_type".to_string(), v.clone()));
            }
            if let Some(v) = &args.description {
                query_params.push(("description".to_string(), v.clone()));
            }
            if let Some(v) = args.include_concealed {
                query_params.push(("include_concealed".to_string(), v.to_string()));
            }
            if let Some(v) = args.is_active {
                query_params.push(("is_active".to_string(), v.to_string()));
            }
            if let Some(v) = args.is_system_role {
                query_params.push(("is_system_role".to_string(), v.to_string()));
            }
            if let Some(v) = &args.name {
                query_params.push(("name".to_string(), v.clone()));
            }
            if let Some(v) = &args.query {
                query_params.push(("query".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/roles/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        RoleCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/roles/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RoleCommand::Create(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::RoleModifyRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let path = "/api/roles/".to_string();
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RoleCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::RoleModifyRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/roles/", uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RoleCommand::Delete(args) => {
            let path = format!("{}{}{}", "/api/roles/", args.uuid, "/");
            let _ = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::DELETE,
                    &path,
                    None,
                )
                .await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
