//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 3usize] = &["uuid", "name", "description"];
///Roles
#[derive(clap::Subcommand, Debug)]
pub enum RoleCommand {
    ///List roles
    List(RoleListArgs),
    ///Get roles
    Get(RoleGetArgs),
    ///Create roles
    Create(RoleCreateArgs),
    ///Update roles
    Update(RoleUpdateArgs),
    ///Delete roles
    Delete(RoleDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct RoleListArgs {
    #[arg(long)]
    pub available_for_customer: Option<String>,
    #[arg(long)]
    pub content_type: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub include_concealed: Option<bool>,
    #[arg(long)]
    pub is_active: Option<bool>,
    #[arg(long)]
    pub is_system_role: Option<bool>,
    #[arg(long)]
    pub name: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub query: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct RoleGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct RoleCreateArgs {
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct RoleUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct RoleDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: RoleCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        RoleCommand::List(args) => {
            let result = client
                .roles_list(
                    args.available_for_customer.as_deref(),
                    args.content_type.as_deref(),
                    args.description.as_deref(),
                    None,
                    args.include_concealed,
                    args.is_active,
                    args.is_system_role,
                    args.name.as_deref(),
                    None,
                    args.page,
                    args.page_size,
                    args.query.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RoleCommand::Get(args) => {
            let result = client.roles_retrieve(args.uuid.as_str(), None).await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RoleCommand::Create(args) => {
            let result = client
                .roles_create(
                    serde_json::from_str::<
                        waldur_client::RoleModifyRequest,
                    >(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RoleCommand::Update(args) => {
            let result = client
                .roles_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<
                        waldur_client::RoleModifyRequest,
                    >(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        RoleCommand::Delete(args) => {
            let _ = client.roles_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
