//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "username", "full_name", "email"];
///Users
#[derive(clap::Subcommand, Debug)]
pub enum UserCommand {
    ///List users
    List(UserListArgs),
    ///Get users
    Get(UserGetArgs),
    ///Create users
    Create(UserCreateArgs),
    ///Update users
    Update(UserUpdateArgs),
    ///Delete users
    Delete(UserDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct UserListArgs {
    #[arg(long)]
    pub agreement_date: Option<String>,
    #[arg(long)]
    pub civil_number: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub date_joined: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub email: Option<String>,
    #[arg(long)]
    pub full_name: Option<String>,
    #[arg(long)]
    pub is_active: Option<bool>,
    #[arg(long)]
    pub is_staff: Option<bool>,
    #[arg(long)]
    pub is_support: Option<bool>,
    #[arg(long)]
    pub job_title: Option<String>,
    #[arg(long)]
    pub modified: Option<String>,
    #[arg(long)]
    pub native_name: Option<String>,
    #[arg(long)]
    pub organization: Option<String>,
    #[arg(long)]
    pub organization_roles: Option<String>,
    #[arg(long)]
    pub phone_number: Option<String>,
    #[arg(long)]
    pub project_roles: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub registration_method: Option<String>,
    #[arg(long)]
    pub user_keyword: Option<String>,
    #[arg(long)]
    pub username: Option<String>,
    #[arg(long)]
    pub username_list: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
}
#[derive(clap::Args, Debug)]
pub struct UserGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct UserCreateArgs {
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct UserUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct UserDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: UserCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        UserCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.agreement_date {
                query_params.push(("agreement_date".to_string(), v.clone()));
            }
            if let Some(v) = &args.civil_number {
                query_params.push(("civil_number".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_uuid {
                query_params.push(("customer_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.date_joined {
                query_params.push(("date_joined".to_string(), v.clone()));
            }
            if let Some(v) = &args.description {
                query_params.push(("description".to_string(), v.clone()));
            }
            if let Some(v) = &args.email {
                query_params.push(("email".to_string(), v.clone()));
            }
            if let Some(v) = &args.full_name {
                query_params.push(("full_name".to_string(), v.clone()));
            }
            if let Some(v) = args.is_active {
                query_params.push(("is_active".to_string(), v.to_string()));
            }
            if let Some(v) = args.is_staff {
                query_params.push(("is_staff".to_string(), v.to_string()));
            }
            if let Some(v) = args.is_support {
                query_params.push(("is_support".to_string(), v.to_string()));
            }
            if let Some(v) = &args.job_title {
                query_params.push(("job_title".to_string(), v.clone()));
            }
            if let Some(v) = &args.modified {
                query_params.push(("modified".to_string(), v.clone()));
            }
            if let Some(v) = &args.native_name {
                query_params.push(("native_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.organization {
                query_params.push(("organization".to_string(), v.clone()));
            }
            if let Some(v) = &args.organization_roles {
                query_params.push(("organization_roles".to_string(), v.clone()));
            }
            if let Some(v) = &args.phone_number {
                query_params.push(("phone_number".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_roles {
                query_params.push(("project_roles".to_string(), v.clone()));
            }
            if let Some(v) = &args.project_uuid {
                query_params.push(("project_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.query {
                query_params.push(("query".to_string(), v.clone()));
            }
            if let Some(v) = &args.registration_method {
                query_params.push(("registration_method".to_string(), v.clone()));
            }
            if let Some(v) = &args.user_keyword {
                query_params.push(("user_keyword".to_string(), v.clone()));
            }
            if let Some(v) = &args.username {
                query_params.push(("username".to_string(), v.clone()));
            }
            if let Some(v) = &args.username_list {
                query_params.push(("username_list".to_string(), v.clone()));
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/users/",
                    &query_params,
                    args.limit,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Get(args) => {
            let result = client.users_retrieve(args.uuid.as_str(), None).await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Create(args) => {
            let result = client
                .users_create(
                    serde_json::from_str::<waldur_client::UserRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Update(args) => {
            let result = client
                .users_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<waldur_client::UserRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Delete(args) => {
            let _ = client.users_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
