//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
use waldur_client::HttpClient;
const COLUMNS: &[&str; 4usize] = &["uuid", "username", "full_name", "email"];
///Users
#[derive(clap::Subcommand, Debug)]
pub enum UserCommand {
    ///List users
    List(UserListArgs),
    ///Get users
    Get(UserGetArgs),
    ///Create users
    Create(UserCreateArgs),
    ///Update users
    Update(UserUpdateArgs),
    ///Delete users
    Delete(UserDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct UserListArgs {
    #[arg(long)]
    pub agreement_date: Option<String>,
    #[arg(long)]
    pub civil_number: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub date_joined: Option<String>,
    #[arg(long)]
    pub description: Option<String>,
    #[arg(long)]
    pub email: Option<String>,
    #[arg(long)]
    pub full_name: Option<String>,
    #[arg(long)]
    pub is_active: Option<bool>,
    #[arg(long)]
    pub is_staff: Option<bool>,
    #[arg(long)]
    pub is_support: Option<bool>,
    #[arg(long)]
    pub job_title: Option<String>,
    #[arg(long)]
    pub modified: Option<String>,
    #[arg(long)]
    pub native_name: Option<String>,
    #[arg(long)]
    pub organization: Option<String>,
    #[arg(long)]
    pub organization_roles: Option<String>,
    #[arg(long)]
    pub page: Option<i64>,
    #[arg(long)]
    pub page_size: Option<i64>,
    #[arg(long)]
    pub phone_number: Option<String>,
    #[arg(long)]
    pub project_roles: Option<String>,
    #[arg(long)]
    pub project_uuid: Option<String>,
    #[arg(long)]
    pub query: Option<String>,
    #[arg(long)]
    pub registration_method: Option<String>,
    #[arg(long)]
    pub user_keyword: Option<String>,
    #[arg(long)]
    pub username: Option<String>,
    #[arg(long)]
    pub username_list: Option<String>,
}
#[derive(clap::Args, Debug)]
pub struct UserGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct UserCreateArgs {
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct UserUpdateArgs {
    pub uuid: String,
    #[arg(long)]
    pub request: String,
}
#[derive(clap::Args, Debug)]
pub struct UserDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    client: &HttpClient,
    command: UserCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        UserCommand::List(args) => {
            let result = client
                .users_list(
                    args.agreement_date.as_deref(),
                    args.civil_number.as_deref(),
                    args.customer_uuid.as_deref(),
                    args.date_joined.as_deref(),
                    args.description.as_deref(),
                    args.email.as_deref(),
                    None,
                    args.full_name.as_deref(),
                    args.is_active,
                    args.is_staff,
                    args.is_support,
                    args.job_title.as_deref(),
                    args.modified.as_deref(),
                    args.native_name.as_deref(),
                    None,
                    args.organization.as_deref(),
                    args.organization_roles.as_deref(),
                    args.page,
                    args.page_size,
                    args.phone_number.as_deref(),
                    args.project_roles.as_deref(),
                    args.project_uuid.as_deref(),
                    args.query.as_deref(),
                    args.registration_method.as_deref(),
                    args.user_keyword.as_deref(),
                    args.username.as_deref(),
                    args.username_list.as_deref(),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Get(args) => {
            let result = client.users_retrieve(args.uuid.as_str(), None).await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Create(args) => {
            let result = client
                .users_create(
                    serde_json::from_str::<waldur_client::UserRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Update(args) => {
            let result = client
                .users_update(
                    args.uuid.as_str(),
                    serde_json::from_str::<waldur_client::UserRequest>(&args.request)
                        .with_context(|| {
                            format!(
                                "--{} is not valid JSON for the expected request body",
                                stringify!(request)
                            )
                        })?,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserCommand::Delete(args) => {
            let _ = client.users_destroy(args.uuid.as_str()).await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
            }
        }
    }
    Ok(())
}
