//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
use anyhow::Context;
const COLUMNS: &[&str; 4usize] = &["uuid", "email", "role_name", "state"];
const CREATE_SKELETON: &str = "{\n  \"civil_number\": null,\n  \"email\": \"\",\n  \"extra_invitation_text\": null,\n  \"full_name\": null,\n  \"job_title\": null,\n  \"native_name\": null,\n  \"organization\": null,\n  \"phone_number\": null,\n  \"role\": \"\",\n  \"scope\": \"\"\n}";
const UPDATE_SKELETON: &str = "{\n  \"email\": \"\",\n  \"role\": null\n}";
///User invitations
#[derive(clap::Subcommand, Debug)]
pub enum UserInvitationCommand {
    ///List user invitations
    List(UserInvitationListArgs),
    ///Get user invitations
    Get(UserInvitationGetArgs),
    ///Create user invitations
    Create(UserInvitationCreateArgs),
    ///Update user invitations
    Update(UserInvitationUpdateArgs),
    ///Delete user invitations
    Delete(UserInvitationDeleteArgs),
}
#[derive(clap::Args, Debug)]
pub struct UserInvitationListArgs {
    #[arg(long)]
    pub civil_number: Option<String>,
    #[arg(long)]
    pub customer_uuid: Option<String>,
    #[arg(long)]
    pub email: Option<String>,
    #[arg(long)]
    pub email_exact: Option<String>,
    #[arg(long)]
    pub role_name: Option<String>,
    #[arg(long)]
    pub role_uuid: Option<String>,
    #[arg(long)]
    pub scope: Option<String>,
    #[arg(long)]
    pub scope_description: Option<String>,
    #[arg(long)]
    pub scope_name: Option<String>,
    #[arg(long)]
    pub scope_type: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(long, value_delimiter = ',')]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct UserInvitationGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "user_invitation_create_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct UserInvitationCreateArgs {
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
#[command(
    group(
        clap::ArgGroup::new(
            "user_invitation_update_body"
        ).required(true).args(["request", "request_file", "generate_skeleton"])
    )
)]
pub struct UserInvitationUpdateArgs {
    pub uuid: Option<String>,
    /// Request body as inline JSON. Use --generate-skeleton for a
    /// template, or --request-file to read it from a file.
    #[arg(long)]
    pub request: Option<String>,
    /// Read the request body from a JSON or YAML file (e.g. a
    /// filled-in --generate-skeleton template).
    #[arg(long, value_name = "PATH")]
    pub request_file: Option<std::path::PathBuf>,
    /// Print a fillable request-body template and exit, instead of
    /// sending a request (json or yaml; default json).
    #[arg(
        long,
        value_enum,
        num_args = 0..= 1,
        default_missing_value = "json",
        value_name = "FORMAT"
    )]
    pub generate_skeleton: Option<crate::request::SkeletonFormat>,
}
#[derive(clap::Args, Debug)]
pub struct UserInvitationDeleteArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    command: UserInvitationCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        UserInvitationCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = Vec::new();
            if let Some(v) = &args.civil_number {
                query_params.push(("civil_number".to_string(), v.clone()));
            }
            if let Some(v) = &args.customer_uuid {
                query_params.push(("customer_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.email {
                query_params.push(("email".to_string(), v.clone()));
            }
            if let Some(v) = &args.email_exact {
                query_params.push(("email_exact".to_string(), v.clone()));
            }
            if let Some(v) = &args.role_name {
                query_params.push(("role_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.role_uuid {
                query_params.push(("role_uuid".to_string(), v.clone()));
            }
            if let Some(v) = &args.scope {
                query_params.push(("scope".to_string(), v.clone()));
            }
            if let Some(v) = &args.scope_description {
                query_params.push(("scope_description".to_string(), v.clone()));
            }
            if let Some(v) = &args.scope_name {
                query_params.push(("scope_name".to_string(), v.clone()));
            }
            if let Some(v) = &args.scope_type {
                query_params.push(("scope_type".to_string(), v.clone()));
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/user-invitations/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        UserInvitationCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/user-invitations/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserInvitationCommand::Create(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(CREATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::InvitationRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let path = "/api/user-invitations/".to_string();
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::POST,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserInvitationCommand::Update(args) => {
            if let Some(fmt) = args.generate_skeleton {
                crate::request::print_skeleton(UPDATE_SKELETON, fmt)?;
                return Ok(());
            }
            let body = crate::request::load_body(
                args.request.as_deref(),
                args.request_file.as_deref(),
            )?;
            serde_json::from_str::<waldur_client::InvitationUpdateRequest>(&body)
                .with_context(|| {
                    "the request body is not valid JSON for this resource's request schema"
                        .to_string()
                })?;
            let uuid = args
                .uuid
                .as_deref()
                .context("this command requires a <uuid> argument")?;
            let path = format!("{}{}{}", "/api/user-invitations/", uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::PUT,
                    &path,
                    Some(&body),
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        UserInvitationCommand::Delete(args) => {
            let path = format!("{}{}{}", "/api/user-invitations/", args.uuid, "/");
            let _ = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::DELETE,
                    &path,
                    None,
                )
                .await?;
            match format {
                crate::output::OutputFormat::Json => {
                    println!(
                        "{}", serde_json::json!({ "deleted" : true, "uuid" : args.uuid })
                    );
                }
                crate::output::OutputFormat::Table => {
                    println!("Deleted {}", args.uuid);
                }
                crate::output::OutputFormat::Tsv => {
                    println!("true\t{}", args.uuid);
                }
                crate::output::OutputFormat::Toon => {
                    println!(
                        "{}", serde_toon::to_string(& serde_json::json!({ "deleted" :
                        true, "uuid" : args.uuid }),) ?
                    );
                }
            }
        }
    }
    Ok(())
}
