//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
const COLUMNS: &[&str; 4usize] = &["uuid", "name", "type", "state"];
const FILTER_SPEC: &[(&str, crate::filter::FilterKind)] = &[
    ("accessible_via_calls", crate::filter::FilterKind::Bool),
    ("allowed_customer_uuid", crate::filter::FilterKind::Str),
    ("attributes", crate::filter::FilterKind::Str),
    ("billable", crate::filter::FilterKind::Bool),
    ("can_create_offering_user", crate::filter::FilterKind::Bool),
    ("category_group_uuid", crate::filter::FilterKind::Str),
    ("category_uuid", crate::filter::FilterKind::Str),
    ("created", crate::filter::FilterKind::Str),
    ("created_before", crate::filter::FilterKind::Str),
    ("customer", crate::filter::FilterKind::Str),
    ("customer_uuid", crate::filter::FilterKind::Str),
    ("description", crate::filter::FilterKind::Str),
    ("has_active_terms_of_service", crate::filter::FilterKind::Bool),
    ("has_terms_of_service", crate::filter::FilterKind::Bool),
    ("keyword", crate::filter::FilterKind::Str),
    ("modified", crate::filter::FilterKind::Str),
    ("modified_before", crate::filter::FilterKind::Str),
    ("name", crate::filter::FilterKind::Str),
    ("name_exact", crate::filter::FilterKind::Str),
    ("o", crate::filter::FilterKind::Str),
    ("offering_group_uuid", crate::filter::FilterKind::Str),
    ("organization_group_uuid", crate::filter::FilterKind::Str),
    ("parent_uuid", crate::filter::FilterKind::Str),
    ("project_uuid", crate::filter::FilterKind::Str),
    ("query", crate::filter::FilterKind::Str),
    ("resource_customer_uuid", crate::filter::FilterKind::Str),
    ("resource_project_uuid", crate::filter::FilterKind::Str),
    ("scope_uuid", crate::filter::FilterKind::Str),
    ("service_manager_uuid", crate::filter::FilterKind::Str),
    ("shared", crate::filter::FilterKind::Bool),
    ("slug", crate::filter::FilterKind::Str),
    ("state", crate::filter::FilterKind::Str),
    ("tag", crate::filter::FilterKind::Str),
    ("tag_name", crate::filter::FilterKind::Str),
    ("tag_names_and", crate::filter::FilterKind::Str),
    ("tags_and", crate::filter::FilterKind::Str),
    ("type", crate::filter::FilterKind::Str),
    ("user_has_consent", crate::filter::FilterKind::Bool),
    ("user_has_offering_user", crate::filter::FilterKind::Bool),
    ("uuid_list", crate::filter::FilterKind::Str),
];
///Marketplace offerings (public)
#[derive(clap::Subcommand, Debug)]
pub enum OfferingCommand {
    ///List marketplace offerings (public)
    List(OfferingListArgs),
    ///Get marketplace offerings (public)
    Get(OfferingGetArgs),
}
#[derive(clap::Args, Debug)]
pub struct OfferingListArgs {
    /// Filter results server-side, KEY=VALUE (repeatable). See
    /// --help's error on an unknown key for the valid keys.
    #[arg(long = "filter", value_name = "KEY=VALUE")]
    pub filter: Vec<String>,
    /// Reshape/narrow the already-fetched result with a JMESPath
    /// expression (https://jmespath.org), client-side -- e.g.
    /// [].name or [?blocked==`true`]. Applied after fetching,
    /// before rendering in --format. (Named distinctly from
    /// --filter's own `query` key, several resources' own
    /// full-text search field.)
    #[arg(long)]
    pub jmespath: Option<String>,
    /// Stop after this many items (across however many pages that
    /// takes), instead of fetching the complete result
    #[arg(long)]
    pub limit: Option<i64>,
    ///Only fetch these fields from the server (comma-separated), instead of the complete object -- avoids over-fetching. Table output always does this already (using its own display columns); for json/toon/tsv, which fetch the complete object by default, this narrows what they get too.
    #[arg(
        long,
        value_delimiter = ',',
        value_parser = clap::builder::PossibleValuesParser::new(
            ["access_url",
            "attributes",
            "backend_id",
            "backend_metadata",
            "billable",
            "billing_type_classification",
            "category",
            "category_title",
            "category_uuid",
            "citation_count",
            "compliance_checklist",
            "components",
            "config_drive_default",
            "country",
            "created",
            "customer",
            "customer_name",
            "customer_uuid",
            "datacite_doi",
            "description",
            "documentation_url",
            "effective_available_limits",
            "endpoints",
            "files",
            "full_description",
            "getting_started",
            "google_calendar_is_public",
            "google_calendar_link",
            "has_compliance_requirements",
            "helpdesk_url",
            "image",
            "integration_guide",
            "is_accessible",
            "latitude",
            "longitude",
            "name",
            "offering_group",
            "offering_group_title",
            "offering_group_uuid",
            "options",
            "order_count",
            "organization_groups",
            "parent_description",
            "parent_name",
            "parent_uuid",
            "partitions",
            "paused_reason",
            "plans",
            "plugin_options",
            "privacy_policy_link",
            "profile_name",
            "profile_uuid",
            "project",
            "project_name",
            "project_uuid",
            "promotion_campaigns",
            "quotas",
            "resource_options",
            "scope",
            "scope_error_message",
            "scope_name",
            "scope_state",
            "scope_uuid",
            "screenshots",
            "secret_options",
            "service_attributes",
            "shared",
            "slug",
            "software_catalogs",
            "state",
            "tags",
            "thumbnail",
            "total_cost",
            "total_cost_estimated",
            "total_customers",
            "type",
            "url",
            "user_has_consent",
            "uuid",
            "vendor_details"]
        ),
    )]
    pub fields: Option<Vec<String>>,
}
#[derive(clap::Args, Debug)]
pub struct OfferingGetArgs {
    pub uuid: String,
}
pub async fn run(
    _client: &waldur_client::HttpClient,
    base_url: &str,
    token: Option<&str>,
    project: Option<&str>,
    command: OfferingCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        OfferingCommand::List(args) => {
            let mut query_params: Vec<(String, String)> = crate::filter::parse_filters(
                &args.filter,
                FILTER_SPEC,
            )?;
            if let Some(project) = project {
                if !query_params.iter().any(|(k, _)| k == "project_uuid") {
                    query_params.push(("project_uuid".to_string(), project.to_string()));
                }
            }
            match &args.fields {
                Some(fields) => {
                    for f in fields {
                        query_params.push(("field".to_string(), f.clone()));
                    }
                }
                None => {
                    if matches!(format, crate ::output::OutputFormat::Table) {
                        for f in COLUMNS {
                            query_params.push(("field".to_string(), (*f).to_string()));
                        }
                    }
                }
            }
            let result = crate::pagination::fetch_all(
                    base_url,
                    token,
                    "/api/marketplace-public-offerings/",
                    &query_params,
                    args.limit,
                )
                .await?;
            let display_columns: Vec<&str> = match &args.fields {
                Some(fields) => fields.iter().map(String::as_str).collect(),
                None => COLUMNS.to_vec(),
            };
            let result: serde_json::Value = serde_json::Value::Array(result);
            let result = match &args.jmespath {
                Some(expr) => crate::query::apply(result, expr)?,
                None => result,
            };
            crate::output::print_result(&result, &display_columns, format)?;
        }
        OfferingCommand::Get(args) => {
            let path = format!(
                "{}{}{}", "/api/marketplace-public-offerings/", args.uuid, "/"
            );
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
    }
    Ok(())
}
