//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand;
//! see that repo's README for how to regenerate.
#![allow(clippy::too_many_arguments)]
const COLUMNS: &[&str; 4usize] = &["uuid", "state", "resource_uuid", "error_message"];
///Marketplace orders (check status of a submitted provision/terminate)
#[derive(clap::Subcommand, Debug)]
pub enum OrderCommand {
    ///Get marketplace orders (check status of a submitted provision/terminate)
    Get(OrderGetArgs),
    ///Wait for a --jmespath condition on marketplace orders (check status of a submitted provision/terminate)
    Wait(OrderWaitArgs),
}
#[derive(clap::Args, Debug)]
pub struct OrderGetArgs {
    pub uuid: String,
}
#[derive(clap::Args, Debug)]
pub struct OrderWaitArgs {
    pub uuid: String,
    /// JMESPath condition to poll for, evaluated against the
    /// fetched object on every poll (e.g. "state=='OK'").
    /// Waiting stops as soon as this evaluates to anything
    /// other than false or null.
    #[arg(long)]
    pub jmespath: String,
    /// Seconds to wait for the condition before giving up.
    #[arg(long, default_value_t = 600)]
    pub timeout: u64,
    /// Seconds between polls.
    #[arg(long, default_value_t = 3)]
    pub interval: u64,
}
pub async fn run(
    base_url: &str,
    token: Option<&str>,
    _project: Option<&str>,
    _dry_run: bool,
    command: OrderCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        OrderCommand::Get(args) => {
            let path = format!("{}{}{}", "/api/marketplace-orders/", args.uuid, "/");
            let result = crate::http::call_one(
                    base_url,
                    token,
                    reqwest::Method::GET,
                    &path,
                    None,
                )
                .await?;
            crate::output::print_result(&result, COLUMNS, format)?;
        }
        OrderCommand::Wait(args) => {
            let path = format!("{}{}{}", "/api/marketplace-orders/", args.uuid, "/");
            crate::wait::wait_for(
                    base_url,
                    token,
                    &path,
                    &args.jmespath,
                    args.timeout,
                    args.interval,
                    COLUMNS,
                    format,
                )
                .await?;
        }
    }
    Ok(())
}
