//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand.
#[derive(clap::Subcommand, Debug)]
pub enum GroupCommand {
    ///Manage OpenStack resources
    #[command(subcommand)]
    Openstack(OpenstackCommand),
    ///Manage team membership and organization access
    #[command(subcommand)]
    Team(TeamCommand),
    ///Browse offerings and provision resources of any offering type
    #[command(subcommand)]
    Marketplace(MarketplaceCommand),
    ///Manage your own authentication credentials (personal access tokens, SSH keys)
    #[command(subcommand)]
    Auth(AuthCommand),
}
///Manage OpenStack resources
#[derive(clap::Subcommand, Debug)]
pub enum OpenstackCommand {
    ///OpenStack tenants
    #[command(subcommand)]
    Tenant(crate::commands::openstack::tenant::TenantCommand),
    ///OpenStack instances (VMs)
    #[command(subcommand)]
    Instance(crate::commands::openstack::instance::InstanceCommand),
    ///OpenStack volumes
    #[command(subcommand)]
    Volume(crate::commands::openstack::volume::VolumeCommand),
    ///OpenStack networks
    #[command(subcommand)]
    Network(crate::commands::openstack::network::NetworkCommand),
    ///OpenStack subnets
    #[command(subcommand)]
    Subnet(crate::commands::openstack::subnet::SubnetCommand),
    ///OpenStack security groups
    #[command(subcommand)]
    SecurityGroup(crate::commands::openstack::security_group::SecurityGroupCommand),
    ///OpenStack floating IPs
    #[command(subcommand)]
    FloatingIp(crate::commands::openstack::floating_ip::FloatingIpCommand),
    ///OpenStack flavors (VM sizes)
    #[command(subcommand)]
    Flavor(crate::commands::openstack::flavor::FlavorCommand),
    ///OpenStack images
    #[command(subcommand)]
    Image(crate::commands::openstack::image::ImageCommand),
}
///Manage team membership and organization access
#[derive(clap::Subcommand, Debug)]
pub enum TeamCommand {
    ///Customers (organizations)
    #[command(subcommand)]
    Customer(crate::commands::team::customer::CustomerCommand),
    ///Projects
    #[command(subcommand)]
    Project(crate::commands::team::project::ProjectCommand),
    ///Users
    #[command(subcommand)]
    User(crate::commands::team::user::UserCommand),
    ///Roles
    #[command(subcommand)]
    Role(crate::commands::team::role::RoleCommand),
}
///Browse offerings and provision resources of any offering type
#[derive(clap::Subcommand, Debug)]
pub enum MarketplaceCommand {
    ///Marketplace offerings (public)
    #[command(subcommand)]
    Offering(crate::commands::marketplace::offering::OfferingCommand),
    ///Marketplace resources (provision/terminate any offering)
    #[command(subcommand)]
    Resource(crate::commands::marketplace::resource::ResourceCommand),
    ///Marketplace orders (check status of a submitted provision/terminate)
    #[command(subcommand)]
    Order(crate::commands::marketplace::order::OrderCommand),
}
///Manage your own authentication credentials (personal access tokens, SSH keys)
#[derive(clap::Subcommand, Debug)]
pub enum AuthCommand {
    ///Personal access tokens (named, scoped, time-limited API credentials)
    #[command(subcommand)]
    PersonalAccessToken(
        crate::commands::auth::personal_access_token::PersonalAccessTokenCommand,
    ),
    ///SSH public keys
    #[command(subcommand)]
    SshKey(crate::commands::auth::ssh_key::SshKeyCommand),
}
pub async fn dispatch(
    base_url: &str,
    token: Option<&str>,
    project: Option<&str>,
    dry_run: bool,
    command: GroupCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        GroupCommand::Openstack(cmd) => {
            match cmd {
                OpenstackCommand::Tenant(cmd) => {
                    crate::commands::openstack::tenant::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::Instance(cmd) => {
                    crate::commands::openstack::instance::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::Volume(cmd) => {
                    crate::commands::openstack::volume::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::Network(cmd) => {
                    crate::commands::openstack::network::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::Subnet(cmd) => {
                    crate::commands::openstack::subnet::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::SecurityGroup(cmd) => {
                    crate::commands::openstack::security_group::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::FloatingIp(cmd) => {
                    crate::commands::openstack::floating_ip::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::Flavor(cmd) => {
                    crate::commands::openstack::flavor::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                OpenstackCommand::Image(cmd) => {
                    crate::commands::openstack::image::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
            }
        }
        GroupCommand::Team(cmd) => {
            match cmd {
                TeamCommand::Customer(cmd) => {
                    crate::commands::team::customer::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                TeamCommand::Project(cmd) => {
                    crate::commands::team::project::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                TeamCommand::User(cmd) => {
                    crate::commands::team::user::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                TeamCommand::Role(cmd) => {
                    crate::commands::team::role::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
            }
        }
        GroupCommand::Marketplace(cmd) => {
            match cmd {
                MarketplaceCommand::Offering(cmd) => {
                    crate::commands::marketplace::offering::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                MarketplaceCommand::Resource(cmd) => {
                    crate::commands::marketplace::resource::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                MarketplaceCommand::Order(cmd) => {
                    crate::commands::marketplace::order::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
            }
        }
        GroupCommand::Auth(cmd) => {
            match cmd {
                AuthCommand::PersonalAccessToken(cmd) => {
                    crate::commands::auth::personal_access_token::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
                AuthCommand::SshKey(cmd) => {
                    crate::commands::auth::ssh_key::run(
                            base_url,
                            token,
                            project,
                            dry_run,
                            cmd,
                            format,
                        )
                        .await
                }
            }
        }
    }
}
