//! Generated by waldur-cli-generator from `commands.toml`. Do not edit by hand.
#[derive(clap::Subcommand, Debug)]
pub enum GroupCommand {
    ///Manage OpenStack resources
    #[command(subcommand)]
    Openstack(OpenstackCommand),
    ///Manage team membership and organization access
    #[command(subcommand)]
    Team(TeamCommand),
}
///Manage OpenStack resources
#[derive(clap::Subcommand, Debug)]
pub enum OpenstackCommand {
    ///OpenStack tenants
    #[command(subcommand)]
    Tenant(crate::commands::openstack::tenant::TenantCommand),
    ///OpenStack instances (VMs)
    #[command(subcommand)]
    Instance(crate::commands::openstack::instance::InstanceCommand),
    ///OpenStack volumes
    #[command(subcommand)]
    Volume(crate::commands::openstack::volume::VolumeCommand),
    ///OpenStack networks
    #[command(subcommand)]
    Network(crate::commands::openstack::network::NetworkCommand),
    ///OpenStack subnets
    #[command(subcommand)]
    Subnet(crate::commands::openstack::subnet::SubnetCommand),
    ///OpenStack security groups
    #[command(subcommand)]
    SecurityGroup(crate::commands::openstack::security_group::SecurityGroupCommand),
    ///OpenStack floating IPs
    #[command(subcommand)]
    FloatingIp(crate::commands::openstack::floating_ip::FloatingIpCommand),
}
///Manage team membership and organization access
#[derive(clap::Subcommand, Debug)]
pub enum TeamCommand {
    ///Customers (organizations)
    #[command(subcommand)]
    Customer(crate::commands::team::customer::CustomerCommand),
    ///Projects
    #[command(subcommand)]
    Project(crate::commands::team::project::ProjectCommand),
    ///Users
    #[command(subcommand)]
    User(crate::commands::team::user::UserCommand),
    ///Roles
    #[command(subcommand)]
    Role(crate::commands::team::role::RoleCommand),
    ///User invitations
    #[command(subcommand)]
    UserInvitation(crate::commands::team::user_invitation::UserInvitationCommand),
    ///Organization groups
    #[command(subcommand)]
    OrganizationGroup(
        crate::commands::team::organization_group::OrganizationGroupCommand,
    ),
    ///Customer permission reviews (read-only)
    #[command(subcommand)]
    CustomerPermissionsReview(
        crate::commands::team::customer_permissions_review::CustomerPermissionsReviewCommand,
    ),
    ///Project permission reviews (read-only)
    #[command(subcommand)]
    ProjectPermissionsReview(
        crate::commands::team::project_permissions_review::ProjectPermissionsReviewCommand,
    ),
    ///User permission requests (read-only)
    #[command(subcommand)]
    UserPermissionRequest(
        crate::commands::team::user_permission_request::UserPermissionRequestCommand,
    ),
}
pub async fn dispatch(
    client: &waldur_client::HttpClient,
    command: GroupCommand,
    format: crate::output::OutputFormat,
) -> anyhow::Result<()> {
    match command {
        GroupCommand::Openstack(cmd) => {
            match cmd {
                OpenstackCommand::Tenant(cmd) => {
                    crate::commands::openstack::tenant::run(client, cmd, format).await
                }
                OpenstackCommand::Instance(cmd) => {
                    crate::commands::openstack::instance::run(client, cmd, format).await
                }
                OpenstackCommand::Volume(cmd) => {
                    crate::commands::openstack::volume::run(client, cmd, format).await
                }
                OpenstackCommand::Network(cmd) => {
                    crate::commands::openstack::network::run(client, cmd, format).await
                }
                OpenstackCommand::Subnet(cmd) => {
                    crate::commands::openstack::subnet::run(client, cmd, format).await
                }
                OpenstackCommand::SecurityGroup(cmd) => {
                    crate::commands::openstack::security_group::run(client, cmd, format)
                        .await
                }
                OpenstackCommand::FloatingIp(cmd) => {
                    crate::commands::openstack::floating_ip::run(client, cmd, format)
                        .await
                }
            }
        }
        GroupCommand::Team(cmd) => {
            match cmd {
                TeamCommand::Customer(cmd) => {
                    crate::commands::team::customer::run(client, cmd, format).await
                }
                TeamCommand::Project(cmd) => {
                    crate::commands::team::project::run(client, cmd, format).await
                }
                TeamCommand::User(cmd) => {
                    crate::commands::team::user::run(client, cmd, format).await
                }
                TeamCommand::Role(cmd) => {
                    crate::commands::team::role::run(client, cmd, format).await
                }
                TeamCommand::UserInvitation(cmd) => {
                    crate::commands::team::user_invitation::run(client, cmd, format)
                        .await
                }
                TeamCommand::OrganizationGroup(cmd) => {
                    crate::commands::team::organization_group::run(client, cmd, format)
                        .await
                }
                TeamCommand::CustomerPermissionsReview(cmd) => {
                    crate::commands::team::customer_permissions_review::run(
                            client,
                            cmd,
                            format,
                        )
                        .await
                }
                TeamCommand::ProjectPermissionsReview(cmd) => {
                    crate::commands::team::project_permissions_review::run(
                            client,
                            cmd,
                            format,
                        )
                        .await
                }
                TeamCommand::UserPermissionRequest(cmd) => {
                    crate::commands::team::user_permission_request::run(
                            client,
                            cmd,
                            format,
                        )
                        .await
                }
            }
        }
    }
}
